graph LR
  E1[".browserslistrc"]
  E2[".devcontainer/Dockerfile"]
  E3[".devcontainer/devcontainer.json"]
  E4[".dockerignore"]
  E5[".github/workflows/build.yml"]
  E6[".github/workflows/netflify.yml"]
  E7[".gitignore"]
  E8[".gitlab-ci.yml"]
  E9[".gitlab/issue_templates/Bug.md"]
  E10[".gitlab/issue_templates/Epic.md"]
  E11[".gitlab/issue_templates/Feature.md"]
  E12[".gitlab/issue_templates/Task.md"]
  E13[".gitlab/issue_templates/TestChecklist.md"]
  E14[".gitlab/issue_templates/user_report.md"]
  E15[".husky/pre-commit"]
  E16[".prettierignore"]
  E17[".prettierrc"]
  E18[".tx/config"]
  E19["Dockerfile"]
  E20["LICENSE.md"]
  E21["README.md"]
  E22["android/.gitignore"]
  E23["android/.project"]
  E24["android/.settings/org.eclipse.buildship.core.prefs"]
  E25["android/app/.npmignore"]
  E26["android/app/build.gradle"]
  E27["android/app/capacitor.build.gradle"]
  E28["android/app/proguard-rules.pro"]
  E29["android/app/src/androidTest/java/com/getcapacitor/myapp/ExampleInstrumentedTest.java"]
  E30["android/app/src/main/AndroidManifest.xml"]
  E31["android/app/src/main/assets/capacitor.config.json"]
  E32["android/app/src/main/assets/capacitor.plugins.json"]
  E33["android/app/src/main/java/it/airgap/vault/MainActivity.java"]
  E34["android/app/src/main/java/it/airgap/vault/plugin/PluginError.kt"]
  E35["android/app/src/main/java/it/airgap/vault/plugin/appinfo/AppInfo.kt"]
  E36["android/app/src/main/java/it/airgap/vault/plugin/camerapreview/CameraFragment.java"]
  E37["android/app/src/main/java/it/airgap/vault/plugin/camerapreview/CameraPreview.kt"]
  E38["android/app/src/main/java/it/airgap/vault/plugin/camerapreview/CustomSurfaceView.java"]
  E39["android/app/src/main/java/it/airgap/vault/plugin/camerapreview/Preview.java"]
  E40["android/app/src/main/java/it/airgap/vault/plugin/camerapreview/TapGestureDetector.java"]
  E41["android/app/src/main/java/it/airgap/vault/plugin/environment/Environment.kt"]
  E42["android/app/src/main/java/it/airgap/vault/plugin/isolatedmodules/FileExplorer.kt"]
  E43["android/app/src/main/java/it/airgap/vault/plugin/isolatedmodules/IsolatedModules.kt"]
  E44["android/app/src/main/java/it/airgap/vault/plugin/isolatedmodules/js/JSEvaluator.kt"]
  E45["android/app/src/main/java/it/airgap/vault/plugin/isolatedmodules/js/JSModule.kt"]
  E46["android/app/src/main/java/it/airgap/vault/plugin/isolatedmodules/js/environment/JSEnvironment.kt"]
  E47["android/app/src/main/java/it/airgap/vault/plugin/isolatedmodules/js/environment/JavaScriptEngineEnvironment.kt"]
  E48["android/app/src/main/java/it/airgap/vault/plugin/isolatedmodules/js/environment/WebViewEnvironment.kt"]
  E49["android/app/src/main/java/it/airgap/vault/plugin/saplingnative/SaplingNative.kt"]
  E50["android/app/src/main/java/it/airgap/vault/plugin/securityutils/AuthOrigin.kt"]
  E51["android/app/src/main/java/it/airgap/vault/plugin/securityutils/SecurityUtils.kt"]
  E52["android/app/src/main/java/it/airgap/vault/plugin/securityutils/authprompt/AuthPromptFragment.kt"]
  E53["android/app/src/main/java/it/airgap/vault/plugin/securityutils/storage/Constants.kt"]
  E54["android/app/src/main/java/it/airgap/vault/plugin/securityutils/storage/Errors.kt"]
  E55["android/app/src/main/java/it/airgap/vault/plugin/securityutils/storage/SecureFile.kt"]
  E56["android/app/src/main/java/it/airgap/vault/plugin/securityutils/storage/SecureFileStorage.kt"]
  E57["android/app/src/main/java/it/airgap/vault/plugin/securityutils/storage/Storage.kt"]
  E58["android/app/src/main/java/it/airgap/vault/plugin/zip/Zip.kt"]
  E59["android/app/src/main/java/it/airgap/vault/util/AnyExtensions.kt"]
  E60["android/app/src/main/java/it/airgap/vault/util/Assets.kt"]
  E61["android/app/src/main/java/it/airgap/vault/util/CollectionExtensions.kt"]
  E62["android/app/src/main/java/it/airgap/vault/util/Deferred.kt"]
  E63["android/app/src/main/java/it/airgap/vault/util/Filesystem.kt"]
  E64["android/app/src/main/java/it/airgap/vault/util/Hex.kt"]
  E65["android/app/src/main/java/it/airgap/vault/util/Interfaces.kt"]
  E66["android/app/src/main/java/it/airgap/vault/util/JS.kt"]
  E67["android/app/src/main/java/it/airgap/vault/util/JSExtensions.kt"]
  E68["android/app/src/main/java/it/airgap/vault/util/PluginExtensions.kt"]
  E69["android/app/src/main/java/it/airgap/vault/util/StringExtensions.kt"]
  E70["android/app/src/main/java/it/airgap/vault/util/ViewExtensions.kt"]
  E71["android/app/src/main/java/it/airgap/vault/util/WebViewExtensions.kt"]
  E72["android/app/src/main/res/drawable-night/splash_icon.xml"]
  E73["android/app/src/main/res/drawable/all_overlay.xml"]
  E74["android/app/src/main/res/drawable/splash_icon.xml"]
  E75["android/app/src/main/res/layout/activity_main.xml"]
  E76["android/app/src/main/res/layout/alert_input_dialog.xml"]
  E77["android/app/src/main/res/layout/alert_setup_dialog.xml"]
  E78["android/app/src/main/res/layout/fragment_authenticator.xml"]
  E79["android/app/src/main/res/layout/fragment_camera.xml"]
  E80["android/app/src/main/res/mipmap-hdpi/ic_launcher.png"]
  E81["android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png"]
  E82["android/app/src/main/res/mipmap-ldpi/ic_launcher.png"]
  E83["android/app/src/main/res/mipmap-ldpi/ic_launcher_round.png"]
  E84["android/app/src/main/res/mipmap-mdpi/ic_launcher.png"]
  E85["android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png"]
  E86["android/app/src/main/res/mipmap-xhdpi/ic_launcher.png"]
  E87["android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png"]
  E88["android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png"]
  E89["android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png"]
  E90["android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png"]
  E91["android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png"]
  E92["android/app/src/main/res/values-night/colors.xml"]
  E93["android/app/src/main/res/values/colors.xml"]
  E94["android/app/src/main/res/values/ic_launcher_background.xml"]
  E95["android/app/src/main/res/values/ids.xml"]
  E96["android/app/src/main/res/values/strings.xml"]
  E97["android/app/src/main/res/values/styles.xml"]
  E98["android/app/src/main/res/xml/config.xml"]
  E99["android/app/src/main/res/xml/file_paths.xml"]
  E100["android/app/src/main/res/xml/network_security_config.xml"]
  E101["android/app/src/test/java/com/getcapacitor/myapp/ExampleUnitTest.java"]
  E102["android/build.gradle"]
  E103["android/capacitor.settings.gradle"]
  E104["android/gradle.properties"]
  E105["android/gradle/wrapper/gradle-wrapper.jar"]
  E106["android/gradle/wrapper/gradle-wrapper.properties"]
  E107["android/gradlew"]
  E108["android/gradlew.bat"]
  E109["android/settings.gradle"]
  E110["android/variables.gradle"]
  E111["angular.json"]
  E112["apple/apple-app-site-association"]
  E113["apply-diagnostic-modules.js"]
  E114["banner.png"]
  E115["build/android/Dockerfile"]
  E116["build/android/debug.keystore"]
  E117["capacitor.config.ts"]
  E118["competencias.yaml"]
  E119["contratos/solflare-keystone.schema.json"]
  E120["copy-builtin-modules.js"]
  E121["devices.png"]
  E122["docs/airgap-vault-kaizou-competences.mmd"]
  E123["docs/airgap-vault-kaizou-concurrency.mmd"]
  E124["docs/airgap-vault-kaizou-dependencies.mmd"]
  E125["docs/airgap-vault-kaizou-flow.mmd"]
  E126["docs/airgap-vault-kaizou-modules.mmd"]
  E127["docs/airgap-vault-kaizou-progress.mmd"]
  E128["e2e/protractor.conf.js"]
  E129["e2e/src/app.e2e-spec.ts"]
  E130["e2e/src/app.po.ts"]
  E131["e2e/tsconfig.e2e.json"]
  E132["electron/.gitignore"]
  E133["electron/capacitor.config.json"]
  E134["electron/index.js"]
  E135["electron/main.js"]
  E136["electron/package-lock.json"]
  E137["electron/package.json"]
  E138["electron/resources/entitlements.mac.plist"]
  E139["electron/resources/icons/icon.png"]
  E140["electron/splash_assets/splash.png"]
  E141["estado.md"]
  E142["fastlane/metadata/android/en-US/full_description.txt"]
  E143["fastlane/metadata/android/en-US/images/icon.png"]
  E144["fastlane/metadata/android/en-US/images/phoneScreenshots/1.png"]
  E145["fastlane/metadata/android/en-US/images/phoneScreenshots/2.png"]
  E146["fastlane/metadata/android/en-US/images/phoneScreenshots/3.png"]
  E147["fastlane/metadata/android/en-US/images/phoneScreenshots/4.png"]
  E148["fastlane/metadata/android/en-US/images/phoneScreenshots/5.png"]
  E149["fastlane/metadata/android/en-US/images/phoneScreenshots/6.png"]
  E150["fastlane/metadata/android/en-US/short_description.txt"]
  E151["fastlane/metadata/android/en-US/title.txt"]
  E152["fastlane/metadata/android/en-US/video.txt"]
  E153["fix-qrscanner-gradle.js"]
  E154["icons/icon-128.webp"]
  E155["icons/icon-192.webp"]
  E156["icons/icon-256.webp"]
  E157["icons/icon-512.webp"]
  E158["icons/icon-72.webp"]
  E159["icons/icon-96.webp"]
  E160["install-build-deps.js"]
  E161["install-test-deps.js"]
  E162["ionic.config.json"]
  E163["ios/.gitignore"]
  E164["ios/App/App.xcodeproj/project.pbxproj"]
  E165["ios/App/App.xcodeproj/project.xcworkspace/contents.xcworkspacedata"]
  E166["ios/App/App.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist"]
  E167["ios/App/App.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved"]
  E168["ios/App/App.xcodeproj/xcshareddata/xcschemes/App.xcscheme"]
  E169["ios/App/App.xcworkspace/contents.xcworkspacedata"]
  E170["ios/App/App.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist"]
  E171["ios/App/App.xcworkspace/xcshareddata/swiftpm/Package.resolved"]
  E172["ios/App/App.xcworkspace/xcshareddata/swiftpm/configuration/Package.resolved"]
  E173["ios/App/App/App-Bridging-Header.h"]
  E174["ios/App/App/AppDelegate.swift"]
  E175["ios/App/App/AppInfo/AppInfo.m"]
  E176["ios/App/App/AppInfo/AppInfo.swift"]
  E177["ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-512@2x.png"]
  E178["ios/App/App/Assets.xcassets/AppIcon.appiconset/Contents.json"]
  E179["ios/App/App/Assets.xcassets/Contents.json"]
  E180["ios/App/App/Assets.xcassets/Splash.imageset/Contents.json"]
  E181["ios/App/App/Assets.xcassets/Splash.imageset/Default@1x~universal~anyany-dark.png"]
  E182["ios/App/App/Assets.xcassets/Splash.imageset/Default@1x~universal~anyany.png"]
  E183["ios/App/App/Assets.xcassets/Splash.imageset/Default@2x~universal~anyany-dark.png"]
  E184["ios/App/App/Assets.xcassets/Splash.imageset/Default@2x~universal~anyany.png"]
  E185["ios/App/App/Assets.xcassets/Splash.imageset/Default@3x~universal~anyany-dark.png"]
  E186["ios/App/App/Assets.xcassets/Splash.imageset/Default@3x~universal~anyany.png"]
  E187["ios/App/App/Base.lproj/LaunchScreen.storyboard"]
  E188["ios/App/App/Base.lproj/Main.storyboard"]
  E189["ios/App/App/Camera/CameraController.swift"]
  E190["ios/App/App/Camera/CameraPreview.m"]
  E191["ios/App/App/Camera/CameraPreview.swift"]
  E192["ios/App/App/Environment/Environment.m"]
  E193["ios/App/App/Environment/Environment.swift"]
  E194["ios/App/App/Helpers/Extensions/Dictionary+Additions.swift"]
  E195["ios/App/App/Helpers/Extensions/JSValue+Additions.swift"]
  E196["ios/App/App/Helpers/Extensions/PluginCall+Additions.swift"]
  E197["ios/App/App/Helpers/Extensions/Sequence+Additions.swift"]
  E198["ios/App/App/Helpers/Extensions/WK+Additions.swift"]
  E199["ios/App/App/Helpers/Filesystem.swift"]
  E200["ios/App/App/Helpers/Hex.swift"]
  E201["ios/App/App/Helpers/JS.swift"]
  E202["ios/App/App/Info.plist"]
  E203["ios/App/App/IsolatedModules/FileExplorer.swift"]
  E204["ios/App/App/IsolatedModules/IsolatedModules.m"]
  E205["ios/App/App/IsolatedModules/IsolatedModules.swift"]
  E206["ios/App/App/IsolatedModules/JS/Environment/JSEnvironment.swift"]
  E207["ios/App/App/IsolatedModules/JS/Environment/WebViewEnvironment.swift"]
  E208["ios/App/App/IsolatedModules/JS/JSEvaluator.swift"]
  E209["ios/App/App/IsolatedModules/JS/JSModule.swift"]
  E210["ios/App/App/IsolatedModules/ModuleManifest.swift"]
  E211["ios/App/App/SaplingNative/SaplingNative.m"]
  E212["ios/App/App/SaplingNative/SaplingNative.swift"]
  E213["ios/App/App/SecurityUtils/DeviceIntegrity.swift"]
  E214["ios/App/App/SecurityUtils/Keychain.swift"]
  E215["ios/App/App/SecurityUtils/LocalAuthentication.swift"]
  E216["ios/App/App/SecurityUtils/SecureScreen.swift"]
  E217["ios/App/App/SecurityUtils/SecureStorage.swift"]
  E218["ios/App/App/SecurityUtils/SecurityUtils.m"]
  E219["ios/App/App/SecurityUtils/SecurityUtils.swift"]
  E220["ios/App/App/SecurityUtils/VaultError.swift"]
  E221["ios/App/App/ViewController.swift"]
  E222["ios/App/App/Zip/Zip.m"]
  E223["ios/App/App/Zip/Zip.swift"]
  E224["ios/App/App/capacitor.config.json"]
  E225["ios/App/App/config.xml"]
  E226["ios/App/Podfile"]
  E227["ios/App/Podfile.lock"]
  E228["lexico.yaml"]
  E229["manifesto.yaml"]
  E230["ngcc.config.js"]
  E231["package.json"]
  E232["patch-dependency-versions.js"]
  E233["resources/logo-dark_splash.svg"]
  E234["resources/logo.svg"]
  E235["resources/logo_splash.svg"]
  E236["resources/splash-dark.svg"]
  E237["resources/splash.svg"]
  E238["script.ts"]
  E239["scripts/airgap-vault-kaizou-generate-diagrams.py"]
  E240["scripts/airgap-vault-kaizou-verify-structure.py"]
  E241["src/app/app-routing.module.ts"]
  E242["src/app/app.component.html"]
  E243["src/app/app.component.spec.ts"]
  E244["src/app/app.component.ts"]
  E245["src/app/app.module.ts"]
  E246["src/app/app.reducers.ts"]
  E247["src/app/app.scss"]
  E248["src/app/capacitor-plugins/definitions.ts"]
  E249["src/app/capacitor-plugins/injection-tokens.ts"]
  E250["src/app/components/add-address/add-address.component.html"]
  E251["src/app/components/add-address/add-address.component.scss"]
  E252["src/app/components/add-address/add-address.component.spec.ts"]
  E253["src/app/components/add-address/add-address.component.ts"]
  E254["src/app/components/components.module.ts"]
  E255["src/app/components/entropy-progress/entropy-progress.component.html"]
  E256["src/app/components/entropy-progress/entropy-progress.component.scss"]
  E257["src/app/components/entropy-progress/entropy-progress.component.spec.ts"]
  E258["src/app/components/entropy-progress/entropy-progress.component.ts"]
  E259["src/app/components/grid-input/grid-input.component.html"]
  E260["src/app/components/grid-input/grid-input.component.scss"]
  E261["src/app/components/grid-input/grid-input.component.spec.ts"]
  E262["src/app/components/grid-input/grid-input.component.ts"]
  E263["src/app/components/interaction-selection/interaction-selection.component.html"]
  E264["src/app/components/interaction-selection/interaction-selection.component.scss"]
  E265["src/app/components/interaction-selection/interaction-selection.component.spec.ts"]
  E266["src/app/components/interaction-selection/interaction-selection.component.ts"]
  E267["src/app/components/keyboard-popover/keyboard-popover.component.html"]
  E268["src/app/components/keyboard-popover/keyboard-popover.component.scss"]
  E269["src/app/components/keyboard-popover/keyboard-popover.component.spec.ts"]
  E270["src/app/components/keyboard-popover/keyboard-popover.component.ts"]
  E271["src/app/components/message-sign-request/message-sign-request.component.html"]
  E272["src/app/components/message-sign-request/message-sign-request.component.scss"]
  E273["src/app/components/message-sign-request/message-sign-request.component.spec.ts"]
  E274["src/app/components/message-sign-request/message-sign-request.component.ts"]
  E275["src/app/components/message-sign-response/message-sign-response.component.html"]
  E276["src/app/components/message-sign-response/message-sign-response.component.scss"]
  E277["src/app/components/message-sign-response/message-sign-response.component.spec.ts"]
  E278["src/app/components/message-sign-response/message-sign-response.component.ts"]
  E279["src/app/components/mnemonic-keyboard/mnemonic-keyboard.component.html"]
  E280["src/app/components/mnemonic-keyboard/mnemonic-keyboard.component.scss"]
  E281["src/app/components/mnemonic-keyboard/mnemonic-keyboard.component.spec.ts"]
  E282["src/app/components/mnemonic-keyboard/mnemonic-keyboard.component.ts"]
  E283["src/app/components/progress-footer/progress-footer.component.html"]
  E284["src/app/components/progress-footer/progress-footer.component.scss"]
  E285["src/app/components/progress-footer/progress-footer.component.spec.ts"]
  E286["src/app/components/progress-footer/progress-footer.component.ts"]
  E287["src/app/components/progress-indicator/progress-indicator.component.html"]
  E288["src/app/components/progress-indicator/progress-indicator.component.scss"]
  E289["src/app/components/progress-indicator/progress-indicator.component.spec.ts"]
  E290["src/app/components/progress-indicator/progress-indicator.component.ts"]
  E291["src/app/components/secret-item/secret-item.component.html"]
  E292["src/app/components/secret-item/secret-item.component.scss"]
  E293["src/app/components/secret-item/secret-item.component.spec.ts"]
  E294["src/app/components/secret-item/secret-item.component.ts"]
  E295["src/app/components/secret-option-item/secret-option-item.component.html"]
  E296["src/app/components/secret-option-item/secret-option-item.component.scss"]
  E297["src/app/components/secret-option-item/secret-option-item.component.spec.ts"]
  E298["src/app/components/secret-option-item/secret-option-item.component.ts"]
  E299["src/app/components/signed-transaction/signed-transaction.component.html"]
  E300["src/app/components/signed-transaction/signed-transaction.component.scss"]
  E301["src/app/components/signed-transaction/signed-transaction.component.spec.ts"]
  E302["src/app/components/signed-transaction/signed-transaction.component.ts"]
  E303["src/app/components/touch-entropy/touch-entropy.component.html"]
  E304["src/app/components/touch-entropy/touch-entropy.component.scss"]
  E305["src/app/components/touch-entropy/touch-entropy.component.spec.ts"]
  E306["src/app/components/touch-entropy/touch-entropy.component.ts"]
  E307["src/app/components/trace-input/trace-input.directive.ts"]
  E308["src/app/components/transaction-warning/transaction-warning.component.html"]
  E309["src/app/components/transaction-warning/transaction-warning.component.scss"]
  E310["src/app/components/transaction-warning/transaction-warning.component.spec.ts"]
  E311["src/app/components/transaction-warning/transaction-warning.component.ts"]
  E312["src/app/components/transaction/transaction.component.html"]
  E313["src/app/components/transaction/transaction.component.scss"]
  E314["src/app/components/transaction/transaction.component.spec.ts"]
  E315["src/app/components/transaction/transaction.component.ts"]
  E316["src/app/components/transaction/transaction.store.ts"]
  E317["src/app/components/verify-key-alt/verify-key-alt.component.html"]
  E318["src/app/components/verify-key-alt/verify-key-alt.component.scss"]
  E319["src/app/components/verify-key-alt/verify-key-alt.component.spec.ts"]
  E320["src/app/components/verify-key-alt/verify-key-alt.component.ts"]
  E321["src/app/components/verify-key/verify-key.component.html"]
  E322["src/app/components/verify-key/verify-key.component.scss"]
  E323["src/app/components/verify-key/verify-key.component.spec.ts"]
  E324["src/app/components/verify-key/verify-key.component.ts"]
  E325["src/app/config/app-config.ts"]
  E326["src/app/constants/constants.ts"]
  E327["src/app/functions/exposed-promise.ts"]
  E328["src/app/models/BIP39Signer.spec.ts"]
  E329["src/app/models/BIP39Signer.ts"]
  E330["src/app/models/BIP85.spec.ts"]
  E331["src/app/models/identifiable.ts"]
  E332["src/app/models/secret.ts"]
  E333["src/app/models/sign-transaction-info.ts"]
  E334["src/app/pages/Installation-type/installation-type.module.ts"]
  E335["src/app/pages/Installation-type/installation-type.page.html"]
  E336["src/app/pages/Installation-type/installation-type.page.scss"]
  E337["src/app/pages/Installation-type/installation-type.page.spec.ts"]
  E338["src/app/pages/Installation-type/installation-type.page.ts"]
  E339["src/app/pages/about/about.module.ts"]
  E340["src/app/pages/about/about.page.html"]
  E341["src/app/pages/about/about.page.scss"]
  E342["src/app/pages/about/about.page.spec.ts"]
  E343["src/app/pages/about/about.page.ts"]
  E344["src/app/pages/account-add/account-add.module.ts"]
  E345["src/app/pages/account-add/account-add.page.html"]
  E346["src/app/pages/account-add/account-add.page.scss"]
  E347["src/app/pages/account-add/account-add.page.spec.ts"]
  E348["src/app/pages/account-add/account-add.page.ts"]
  E349["src/app/pages/account-address/account-address.module.ts"]
  E350["src/app/pages/account-address/account-address.page.html"]
  E351["src/app/pages/account-address/account-address.page.scss"]
  E352["src/app/pages/account-address/account-address.page.spec.ts"]
  E353["src/app/pages/account-address/account-address.page.ts"]
  E354["src/app/pages/account-address/account-edit-popover/account-edit-popover.component.html"]
  E355["src/app/pages/account-address/account-edit-popover/account-edit-popover.component.scss"]
  E356["src/app/pages/account-address/account-edit-popover/account-edit-popover.component.spec.ts"]
  E357["src/app/pages/account-address/account-edit-popover/account-edit-popover.component.ts"]
  E358["src/app/pages/account-share-select/account-share-select-routing.module.ts"]
  E359["src/app/pages/account-share-select/account-share-select.actions.ts"]
  E360["src/app/pages/account-share-select/account-share-select.effects.ts"]
  E361["src/app/pages/account-share-select/account-share-select.module.ts"]
  E362["src/app/pages/account-share-select/account-share-select.page.html"]
  E363["src/app/pages/account-share-select/account-share-select.page.scss"]
  E364["src/app/pages/account-share-select/account-share-select.page.spec.ts"]
  E365["src/app/pages/account-share-select/account-share-select.page.ts"]
  E366["src/app/pages/account-share-select/account-share-select.reducers.ts"]
  E367["src/app/pages/account-share-select/account-share-select.types.ts"]
  E368["src/app/pages/account-share/account-share.module.ts"]
  E369["src/app/pages/account-share/account-share.page.html"]
  E370["src/app/pages/account-share/account-share.page.scss"]
  E371["src/app/pages/account-share/account-share.page.spec.ts"]
  E372["src/app/pages/account-share/account-share.page.ts"]
  E373["src/app/pages/accounts-list/accounts-list-edit-popover/accounts-list-edit-popover.component.html"]
  E374["src/app/pages/accounts-list/accounts-list-edit-popover/accounts-list-edit-popover.component.scss"]
  E375["src/app/pages/accounts-list/accounts-list-edit-popover/accounts-list-edit-popover.component.spec.ts"]
  E376["src/app/pages/accounts-list/accounts-list-edit-popover/accounts-list-edit-popover.component.ts"]
  E377["src/app/pages/accounts-list/accounts-list-routing.module.ts"]
  E378["src/app/pages/accounts-list/accounts-list.module.ts"]
  E379["src/app/pages/accounts-list/accounts-list.page.html"]
  E380["src/app/pages/accounts-list/accounts-list.page.scss"]
  E381["src/app/pages/accounts-list/accounts-list.page.spec.ts"]
  E382["src/app/pages/accounts-list/accounts-list.page.ts"]
  E383["src/app/pages/address-explorer/address-explorer-routing.module.ts"]
  E384["src/app/pages/address-explorer/address-explorer.module.ts"]
  E385["src/app/pages/address-explorer/address-explorer.page.html"]
  E386["src/app/pages/address-explorer/address-explorer.page.scss"]
  E387["src/app/pages/address-explorer/address-explorer.page.spec.ts"]
  E388["src/app/pages/address-explorer/address-explorer.page.ts"]
  E389["src/app/pages/advanced-mode/advanced-mode.module.ts"]
  E390["src/app/pages/advanced-mode/advanced-mode.page.html"]
  E391["src/app/pages/advanced-mode/advanced-mode.page.scss"]
  E392["src/app/pages/advanced-mode/advanced-mode.page.spec.ts"]
  E393["src/app/pages/advanced-mode/advanced-mode.page.ts"]
  E394["src/app/pages/bip85-generate/bip85-generate-routing.module.ts"]
  E395["src/app/pages/bip85-generate/bip85-generate.module.ts"]
  E396["src/app/pages/bip85-generate/bip85-generate.page.html"]
  E397["src/app/pages/bip85-generate/bip85-generate.page.scss"]
  E398["src/app/pages/bip85-generate/bip85-generate.page.spec.ts"]
  E399["src/app/pages/bip85-generate/bip85-generate.page.ts"]
  E400["src/app/pages/bip85-show/bip85-show-routing.module.ts"]
  E401["src/app/pages/bip85-show/bip85-show.module.ts"]
  E402["src/app/pages/bip85-show/bip85-show.page.html"]
  E403["src/app/pages/bip85-show/bip85-show.page.scss"]
  E404["src/app/pages/bip85-show/bip85-show.page.spec.ts"]
  E405["src/app/pages/bip85-show/bip85-show.page.ts"]
  E406["src/app/pages/contact-book-contacts-detail/contact-book-contacts-detail.module.ts"]
  E407["src/app/pages/contact-book-contacts-detail/contact-book-contacts-detail.page.html"]
  E408["src/app/pages/contact-book-contacts-detail/contact-book-contacts-detail.page.scss"]
  E409["src/app/pages/contact-book-contacts-detail/contact-book-contacts-detail.page.spec.ts"]
  E410["src/app/pages/contact-book-contacts-detail/contact-book-contacts-detail.page.ts"]
  E411["src/app/pages/contact-book-contacts/contact-book-contacts-item/contact-book-contacts-item.component.html"]
  E412["src/app/pages/contact-book-contacts/contact-book-contacts-item/contact-book-contacts-item.component.scss"]
  E413["src/app/pages/contact-book-contacts/contact-book-contacts-item/contact-book-contacts-item.component.ts"]
  E414["src/app/pages/contact-book-contacts/contact-book-contacts-item/tab-secret-popover.component.spec.ts"]
  E415["src/app/pages/contact-book-contacts/contact-book-contacts-popover/contact-book-contacts-popover.component.html"]
  E416["src/app/pages/contact-book-contacts/contact-book-contacts-popover/contact-book-contacts-popover.component.scss"]
  E417["src/app/pages/contact-book-contacts/contact-book-contacts-popover/contact-book-contacts-popover.component.ts"]
  E418["src/app/pages/contact-book-contacts/contact-book-contacts-popover/tab-secret-popover.component.spec.ts"]
  E419["src/app/pages/contact-book-contacts/contact-book-contacts-suggestion/contact-book-contacts-suggestion.component.html"]
  E420["src/app/pages/contact-book-contacts/contact-book-contacts-suggestion/contact-book-contacts-suggestion.component.scss"]
  E421["src/app/pages/contact-book-contacts/contact-book-contacts-suggestion/contact-book-contacts-suggestion.component.spec.ts"]
  E422["src/app/pages/contact-book-contacts/contact-book-contacts-suggestion/contact-book-contacts-suggestion.component.ts"]
  E423["src/app/pages/contact-book-contacts/contact-book-contacts.module.ts"]
  E424["src/app/pages/contact-book-contacts/contact-book-contacts.page.html"]
  E425["src/app/pages/contact-book-contacts/contact-book-contacts.page.scss"]
  E426["src/app/pages/contact-book-contacts/contact-book-contacts.page.spec.ts"]
  E427["src/app/pages/contact-book-contacts/contact-book-contacts.page.ts"]
  E428["src/app/pages/contact-book-onboarding/contact-book-onboarding.module.ts"]
  E429["src/app/pages/contact-book-onboarding/contact-book-onboarding.page.html"]
  E430["src/app/pages/contact-book-onboarding/contact-book-onboarding.page.scss"]
  E431["src/app/pages/contact-book-onboarding/contact-book-onboarding.page.spec.ts"]
  E432["src/app/pages/contact-book-onboarding/contact-book-onboarding.page.ts"]
  E433["src/app/pages/contact-book-scan/contact-book-scan.component.html"]
  E434["src/app/pages/contact-book-scan/contact-book-scan.component.scss"]
  E435["src/app/pages/contact-book-scan/contact-book-scan.component.spec.ts"]
  E436["src/app/pages/contact-book-scan/contact-book-scan.module.ts"]
  E437["src/app/pages/contact-book-scan/contact-book-scan.page.ts"]
  E438["src/app/pages/contact-book-settings/contact-book-settings.module.ts"]
  E439["src/app/pages/contact-book-settings/contact-book-settings.page.html"]
  E440["src/app/pages/contact-book-settings/contact-book-settings.page.scss"]
  E441["src/app/pages/contact-book-settings/contact-book-settings.page.spec.ts"]
  E442["src/app/pages/contact-book-settings/contact-book-settings.page.ts"]
  E443["src/app/pages/deserialized-detail/deserialized-detail.actions.ts"]
  E444["src/app/pages/deserialized-detail/deserialized-detail.effects.ts"]
  E445["src/app/pages/deserialized-detail/deserialized-detail.module.ts"]
  E446["src/app/pages/deserialized-detail/deserialized-detail.page.html"]
  E447["src/app/pages/deserialized-detail/deserialized-detail.page.scss"]
  E448["src/app/pages/deserialized-detail/deserialized-detail.page.spec.ts"]
  E449["src/app/pages/deserialized-detail/deserialized-detail.page.ts"]
  E450["src/app/pages/deserialized-detail/deserialized-detail.reducer.ts"]
  E451["src/app/pages/deserialized-detail/deserialized.detail.types.ts"]
  E452["src/app/pages/distribution-onboarding/distribution-onboarding.module.ts"]
  E453["src/app/pages/distribution-onboarding/distribution-onboarding.page.html"]
  E454["src/app/pages/distribution-onboarding/distribution-onboarding.page.scss"]
  E455["src/app/pages/distribution-onboarding/distribution-onboarding.page.spec.ts"]
  E456["src/app/pages/distribution-onboarding/distribution-onboarding.page.ts"]
  E457["src/app/pages/error-history/error-history-routing.module.ts"]
  E458["src/app/pages/error-history/error-history.module.ts"]
  E459["src/app/pages/error-history/error-history.page.html"]
  E460["src/app/pages/error-history/error-history.page.scss"]
  E461["src/app/pages/error-history/error-history.page.spec.ts"]
  E462["src/app/pages/error-history/error-history.page.ts"]
  E463["src/app/pages/interaction-selection-settings/interaction-selection-settings.module.ts"]
  E464["src/app/pages/interaction-selection-settings/interaction-selection-settings.page.html"]
  E465["src/app/pages/interaction-selection-settings/interaction-selection-settings.page.scss"]
  E466["src/app/pages/interaction-selection-settings/interaction-selection-settings.page.spec.ts"]
  E467["src/app/pages/interaction-selection-settings/interaction-selection-settings.page.ts"]
  E468["src/app/pages/interaction-selection/interaction-selection.module.ts"]
  E469["src/app/pages/interaction-selection/interaction-selection.page.html"]
  E470["src/app/pages/interaction-selection/interaction-selection.page.scss"]
  E471["src/app/pages/interaction-selection/interaction-selection.page.spec.ts"]
  E472["src/app/pages/interaction-selection/interaction-selection.page.ts"]
  E473["src/app/pages/introduction/introduction.module.ts"]
  E474["src/app/pages/introduction/introduction.page.html"]
  E475["src/app/pages/introduction/introduction.page.scss"]
  E476["src/app/pages/introduction/introduction.page.spec.ts"]
  E477["src/app/pages/introduction/introduction.page.ts"]
  E478["src/app/pages/isolated-modules-details/isolated-modules-details.module.ts"]
  E479["src/app/pages/isolated-modules-details/isolated-modules-details.page.html"]
  E480["src/app/pages/isolated-modules-details/isolated-modules-details.page.scss"]
  E481["src/app/pages/isolated-modules-details/isolated-modules-details.page.spec.ts"]
  E482["src/app/pages/isolated-modules-details/isolated-modules-details.page.ts"]
  E483["src/app/pages/isolated-modules-details/isolated-modules.details.types.ts"]
  E484["src/app/pages/isolated-modules-details/popover/isolated-modules-details-popover.component.html"]
  E485["src/app/pages/isolated-modules-details/popover/isolated-modules-details-popover.component.scss"]
  E486["src/app/pages/isolated-modules-details/popover/isolated-modules-details-popover.component.spec.ts"]
  E487["src/app/pages/isolated-modules-details/popover/isolated-modules-details-popover.component.ts"]
  E488["src/app/pages/isolated-modules-list/isolated-modules-list-routing.module.ts"]
  E489["src/app/pages/isolated-modules-list/isolated-modules-list.module.ts"]
  E490["src/app/pages/isolated-modules-list/isolated-modules-list.page.html"]
  E491["src/app/pages/isolated-modules-list/isolated-modules-list.page.scss"]
  E492["src/app/pages/isolated-modules-list/isolated-modules-list.page.spec.ts"]
  E493["src/app/pages/isolated-modules-list/isolated-modules-list.page.ts"]
  E494["src/app/pages/isolated-modules-onboarding/isolated-modules-onboarding.module.ts"]
  E495["src/app/pages/isolated-modules-onboarding/isolated-modules-onboarding.page.html"]
  E496["src/app/pages/isolated-modules-onboarding/isolated-modules-onboarding.page.scss"]
  E497["src/app/pages/isolated-modules-onboarding/isolated-modules-onboarding.page.spec.ts"]
  E498["src/app/pages/isolated-modules-onboarding/isolated-modules-onboarding.page.ts"]
  E499["src/app/pages/languages-selection-settings/languages-selection-settings.module.ts"]
  E500["src/app/pages/languages-selection-settings/languages-selection-settings.page.html"]
  E501["src/app/pages/languages-selection-settings/languages-selection-settings.page.scss"]
  E502["src/app/pages/languages-selection-settings/languages-selection-settings.page.spec.ts"]
  E503["src/app/pages/languages-selection-settings/languages-selection-settings.page.ts"]
  E504["src/app/pages/link-page/link-page-routing.module.ts"]
  E505["src/app/pages/link-page/link-page.module.ts"]
  E506["src/app/pages/link-page/link-page.page.html"]
  E507["src/app/pages/link-page/link-page.page.scss"]
  E508["src/app/pages/link-page/link-page.page.spec.ts"]
  E509["src/app/pages/link-page/link-page.page.ts"]
  E510["src/app/pages/local-authentication-onboarding/local-authentication-onboarding.module.ts"]
  E511["src/app/pages/local-authentication-onboarding/local-authentication-onboarding.page.html"]
  E512["src/app/pages/local-authentication-onboarding/local-authentication-onboarding.page.scss"]
  E513["src/app/pages/local-authentication-onboarding/local-authentication-onboarding.page.spec.ts"]
  E514["src/app/pages/local-authentication-onboarding/local-authentication-onboarding.page.ts"]
  E515["src/app/pages/migration/migration-routing.module.ts"]
  E516["src/app/pages/migration/migration.actions.ts"]
  E517["src/app/pages/migration/migration.effects.ts"]
  E518["src/app/pages/migration/migration.module.ts"]
  E519["src/app/pages/migration/migration.page.html"]
  E520["src/app/pages/migration/migration.page.scss"]
  E521["src/app/pages/migration/migration.page.spec.ts"]
  E522["src/app/pages/migration/migration.page.ts"]
  E523["src/app/pages/migration/migration.reducers.ts"]
  E524["src/app/pages/migration/migration.types.ts"]
  E525["src/app/pages/migration/migration.utils.ts"]
  E526["src/app/pages/onboarding-advanced-mode/onboarding-advanced-mode.module.ts"]
  E527["src/app/pages/onboarding-advanced-mode/onboarding-advanced-mode.page.html"]
  E528["src/app/pages/onboarding-advanced-mode/onboarding-advanced-mode.page.scss"]
  E529["src/app/pages/onboarding-advanced-mode/onboarding-advanced-mode.page.spec.ts"]
  E530["src/app/pages/onboarding-advanced-mode/onboarding-advanced-mode.page.ts"]
  E531["src/app/pages/onboarding-welcome/onboarding-welcome.module.ts"]
  E532["src/app/pages/onboarding-welcome/onboarding-welcome.page.html"]
  E533["src/app/pages/onboarding-welcome/onboarding-welcome.page.scss"]
  E534["src/app/pages/onboarding-welcome/onboarding-welcome.page.spec.ts"]
  E535["src/app/pages/onboarding-welcome/onboarding-welcome.page.ts"]
  E536["src/app/pages/qr-settings/qr-settings-routing.module.ts"]
  E537["src/app/pages/qr-settings/qr-settings.module.ts"]
  E538["src/app/pages/qr-settings/qr-settings.page.html"]
  E539["src/app/pages/qr-settings/qr-settings.page.scss"]
  E540["src/app/pages/qr-settings/qr-settings.page.spec.ts"]
  E541["src/app/pages/qr-settings/qr-settings.page.ts"]
  E542["src/app/pages/scan-base/scan-base.ts"]
  E543["src/app/pages/secret-add/secret-add.module.ts"]
  E544["src/app/pages/secret-add/secret-add.page.html"]
  E545["src/app/pages/secret-add/secret-add.page.scss"]
  E546["src/app/pages/secret-add/secret-add.page.spec.ts"]
  E547["src/app/pages/secret-add/secret-add.page.ts"]
  E548["src/app/pages/secret-edit/secret-edit.module.ts"]
  E549["src/app/pages/secret-edit/secret-edit.page.html"]
  E550["src/app/pages/secret-edit/secret-edit.page.scss"]
  E551["src/app/pages/secret-edit/secret-edit.page.spec.ts"]
  E552["src/app/pages/secret-edit/secret-edit.page.ts"]
  E553["src/app/pages/secret-generate-coin-flip/secret-generate-coin-flip-routing.module.ts"]
  E554["src/app/pages/secret-generate-coin-flip/secret-generate-coin-flip.module.ts"]
  E555["src/app/pages/secret-generate-coin-flip/secret-generate-coin-flip.page.html"]
  E556["src/app/pages/secret-generate-coin-flip/secret-generate-coin-flip.page.scss"]
  E557["src/app/pages/secret-generate-coin-flip/secret-generate-coin-flip.page.spec.ts"]
  E558["src/app/pages/secret-generate-coin-flip/secret-generate-coin-flip.page.ts"]
  E559["src/app/pages/secret-generate-dice/secret-generate-dice-routing.module.ts"]
  E560["src/app/pages/secret-generate-dice/secret-generate-dice.module.ts"]
  E561["src/app/pages/secret-generate-dice/secret-generate-dice.page.html"]
  E562["src/app/pages/secret-generate-dice/secret-generate-dice.page.scss"]
  E563["src/app/pages/secret-generate-dice/secret-generate-dice.page.spec.ts"]
  E564["src/app/pages/secret-generate-dice/secret-generate-dice.page.ts"]
  E565["src/app/pages/secret-generate-onboarding/secret-generate-onboarding.module.ts"]
  E566["src/app/pages/secret-generate-onboarding/secret-generate-onboarding.page.html"]
  E567["src/app/pages/secret-generate-onboarding/secret-generate-onboarding.page.scss"]
  E568["src/app/pages/secret-generate-onboarding/secret-generate-onboarding.page.spec.ts"]
  E569["src/app/pages/secret-generate-onboarding/secret-generate-onboarding.page.ts"]
  E570["src/app/pages/secret-generate/secret-generate.module.ts"]
  E571["src/app/pages/secret-generate/secret-generate.page.html"]
  E572["src/app/pages/secret-generate/secret-generate.page.scss"]
  E573["src/app/pages/secret-generate/secret-generate.page.spec.ts"]
  E574["src/app/pages/secret-generate/secret-generate.page.ts"]
  E575["src/app/pages/secret-import/secret-import.module.ts"]
  E576["src/app/pages/secret-import/secret-import.page.html"]
  E577["src/app/pages/secret-import/secret-import.page.scss"]
  E578["src/app/pages/secret-import/secret-import.page.spec.ts"]
  E579["src/app/pages/secret-import/secret-import.page.ts"]
  E580["src/app/pages/secret-rules/secret-rules.module.ts"]
  E581["src/app/pages/secret-rules/secret-rules.page.html"]
  E582["src/app/pages/secret-rules/secret-rules.page.scss"]
  E583["src/app/pages/secret-rules/secret-rules.page.spec.ts"]
  E584["src/app/pages/secret-rules/secret-rules.page.ts"]
  E585["src/app/pages/secret-setup/secret-setup.module.ts"]
  E586["src/app/pages/secret-setup/secret-setup.page.html"]
  E587["src/app/pages/secret-setup/secret-setup.page.scss"]
  E588["src/app/pages/secret-setup/secret-setup.page.spec.ts"]
  E589["src/app/pages/secret-setup/secret-setup.page.ts"]
  E590["src/app/pages/secret-show/secret-show.module.ts"]
  E591["src/app/pages/secret-show/secret-show.page.html"]
  E592["src/app/pages/secret-show/secret-show.page.scss"]
  E593["src/app/pages/secret-show/secret-show.page.spec.ts"]
  E594["src/app/pages/secret-show/secret-show.page.ts"]
  E595["src/app/pages/secret-validate/secret-validate.module.ts"]
  E596["src/app/pages/secret-validate/secret-validate.page.html"]
  E597["src/app/pages/secret-validate/secret-validate.page.scss"]
  E598["src/app/pages/secret-validate/secret-validate.page.spec.ts"]
  E599["src/app/pages/secret-validate/secret-validate.page.ts"]
  E600["src/app/pages/security-level-self-check/security-level-self-check.module.ts"]
  E601["src/app/pages/security-level-self-check/security-level-self-check.page.html"]
  E602["src/app/pages/security-level-self-check/security-level-self-check.page.scss"]
  E603["src/app/pages/security-level-self-check/security-level-self-check.page.spec.ts"]
  E604["src/app/pages/security-level-self-check/security-level-self-check.page.ts"]
  E605["src/app/pages/select-account/select-account.module.ts"]
  E606["src/app/pages/select-account/select-account.page.html"]
  E607["src/app/pages/select-account/select-account.page.scss"]
  E608["src/app/pages/select-account/select-account.page.spec.ts"]
  E609["src/app/pages/select-account/select-account.page.ts"]
  E610["src/app/pages/shop/shop.module.ts"]
  E611["src/app/pages/shop/shop.page.html"]
  E612["src/app/pages/shop/shop.page.scss"]
  E613["src/app/pages/shop/shop.page.spec.ts"]
  E614["src/app/pages/shop/shop.page.ts"]
  E615["src/app/pages/social-recovery-generate-finish/social-recovery-generate-finish.module.ts"]
  E616["src/app/pages/social-recovery-generate-finish/social-recovery-generate-finish.page.html"]
  E617["src/app/pages/social-recovery-generate-finish/social-recovery-generate-finish.page.scss"]
  E618["src/app/pages/social-recovery-generate-finish/social-recovery-generate-finish.page.ts"]
  E619["src/app/pages/social-recovery-generate-finish/social-recovery-generate-finish.spec.ts"]
  E620["src/app/pages/social-recovery-generate-intro/social-recovery-generate-intro.module.ts"]
  E621["src/app/pages/social-recovery-generate-intro/social-recovery-generate-intro.page.html"]
  E622["src/app/pages/social-recovery-generate-intro/social-recovery-generate-intro.page.scss"]
  E623["src/app/pages/social-recovery-generate-intro/social-recovery-generate-intro.page.ts"]
  E624["src/app/pages/social-recovery-generate-intro/social-recovery-generate-intro.spec.ts"]
  E625["src/app/pages/social-recovery-generate-rules/social-recovery-generate-rules.module.ts"]
  E626["src/app/pages/social-recovery-generate-rules/social-recovery-generate-rules.page.html"]
  E627["src/app/pages/social-recovery-generate-rules/social-recovery-generate-rules.page.scss"]
  E628["src/app/pages/social-recovery-generate-rules/social-recovery-generate-rules.page.ts"]
  E629["src/app/pages/social-recovery-generate-rules/social-recovery-generate-rules.spec.ts"]
  E630["src/app/pages/social-recovery-generate-setup/social-recovery-generate-setup.module.ts"]
  E631["src/app/pages/social-recovery-generate-setup/social-recovery-generate-setup.page.html"]
  E632["src/app/pages/social-recovery-generate-setup/social-recovery-generate-setup.page.scss"]
  E633["src/app/pages/social-recovery-generate-setup/social-recovery-generate-setup.page.ts"]
  E634["src/app/pages/social-recovery-generate-setup/social-recovery-generate-setup.spec.ts"]
  E635["src/app/pages/social-recovery-generate-share-show/social-recovery-generate-share-show.module.ts"]
  E636["src/app/pages/social-recovery-generate-share-show/social-recovery-generate-share-show.page.html"]
  E637["src/app/pages/social-recovery-generate-share-show/social-recovery-generate-share-show.page.scss"]
  E638["src/app/pages/social-recovery-generate-share-show/social-recovery-generate-share-show.page.ts"]
  E639["src/app/pages/social-recovery-generate-share-show/social-recovery-generate-share-show.spec.ts"]
  E640["src/app/pages/social-recovery-generate-share-validate/social-recovery-generate-share-validate.module.ts"]
  E641["src/app/pages/social-recovery-generate-share-validate/social-recovery-generate-share-validate.page.html"]
  E642["src/app/pages/social-recovery-generate-share-validate/social-recovery-generate-share-validate.page.scss"]
  E643["src/app/pages/social-recovery-generate-share-validate/social-recovery-generate-share-validate.page.ts"]
  E644["src/app/pages/social-recovery-generate-share-validate/social-recovery-generate-share-validate.spec.ts"]
  E645["src/app/pages/social-recovery-import-errors/social-recovery-import-errors.module.ts"]
  E646["src/app/pages/social-recovery-import-errors/social-recovery-import-errors.page.html"]
  E647["src/app/pages/social-recovery-import-errors/social-recovery-import-errors.page.scss"]
  E648["src/app/pages/social-recovery-import-errors/social-recovery-import-errors.page.spec.ts"]
  E649["src/app/pages/social-recovery-import-errors/social-recovery-import-errors.page.ts"]
  E650["src/app/pages/social-recovery-import-help/social-recovery-import-help.module.ts"]
  E651["src/app/pages/social-recovery-import-help/social-recovery-import-help.page.html"]
  E652["src/app/pages/social-recovery-import-help/social-recovery-import-help.page.scss"]
  E653["src/app/pages/social-recovery-import-help/social-recovery-import-help.page.spec.ts"]
  E654["src/app/pages/social-recovery-import-help/social-recovery-import-help.page.ts"]
  E655["src/app/pages/social-recovery-import-intro/social-recovery-import-intro.module.ts"]
  E656["src/app/pages/social-recovery-import-intro/social-recovery-import-intro.page.html"]
  E657["src/app/pages/social-recovery-import-intro/social-recovery-import-intro.page.scss"]
  E658["src/app/pages/social-recovery-import-intro/social-recovery-import-intro.page.spec.ts"]
  E659["src/app/pages/social-recovery-import-intro/social-recovery-import-intro.page.ts"]
  E660["src/app/pages/social-recovery-import-setup/social-recovery-import-setup.module.ts"]
  E661["src/app/pages/social-recovery-import-setup/social-recovery-import-setup.page.html"]
  E662["src/app/pages/social-recovery-import-setup/social-recovery-import-setup.page.scss"]
  E663["src/app/pages/social-recovery-import-setup/social-recovery-import-setup.page.spec.ts"]
  E664["src/app/pages/social-recovery-import-setup/social-recovery-import-setup.page.ts"]
  E665["src/app/pages/social-recovery-import-share-name/social-recovery-import-share-name.module.ts"]
  E666["src/app/pages/social-recovery-import-share-name/social-recovery-import-share-name.page.html"]
  E667["src/app/pages/social-recovery-import-share-name/social-recovery-import-share-name.page.scss"]
  E668["src/app/pages/social-recovery-import-share-name/social-recovery-import-share-name.page.spec.ts"]
  E669["src/app/pages/social-recovery-import-share-name/social-recovery-import-share-name.page.ts"]
  E670["src/app/pages/social-recovery-import-share-validate/social-recovery-import-share-validate.module.ts"]
  E671["src/app/pages/social-recovery-import-share-validate/social-recovery-import-share-validate.page.html"]
  E672["src/app/pages/social-recovery-import-share-validate/social-recovery-import-share-validate.page.scss"]
  E673["src/app/pages/social-recovery-import-share-validate/social-recovery-import-share-validate.page.spec.ts"]
  E674["src/app/pages/social-recovery-import-share-validate/social-recovery-import-share-validate.page.ts"]
  E675["src/app/pages/social-recovery-import-success/social-recovery-import-success.module.ts"]
  E676["src/app/pages/social-recovery-import-success/social-recovery-import-success.page.html"]
  E677["src/app/pages/social-recovery-import-success/social-recovery-import-success.page.scss"]
  E678["src/app/pages/social-recovery-import-success/social-recovery-import-success.page.spec.ts"]
  E679["src/app/pages/social-recovery-import-success/social-recovery-import-success.page.ts"]
  E680["src/app/pages/social-recovery-import/social-recovery-import.module.ts"]
  E681["src/app/pages/social-recovery-import/social-recovery-import.page.html"]
  E682["src/app/pages/social-recovery-import/social-recovery-import.page.scss"]
  E683["src/app/pages/social-recovery-import/social-recovery-import.page.spec.ts"]
  E684["src/app/pages/social-recovery-import/social-recovery-import.page.ts"]
  E685["src/app/pages/social-recovery-setup/social-recovery-setup.module.ts"]
  E686["src/app/pages/social-recovery-setup/social-recovery-setup.page.html"]
  E687["src/app/pages/social-recovery-setup/social-recovery-setup.page.scss"]
  E688["src/app/pages/social-recovery-setup/social-recovery-setup.page.spec.ts"]
  E689["src/app/pages/social-recovery-setup/social-recovery-setup.page.ts"]
  E690["src/app/pages/social-recovery-show-share/social-recovery-show-share.module.ts"]
  E691["src/app/pages/social-recovery-show-share/social-recovery-show-share.page.html"]
  E692["src/app/pages/social-recovery-show-share/social-recovery-show-share.page.scss"]
  E693["src/app/pages/social-recovery-show-share/social-recovery-show-share.page.spec.ts"]
  E694["src/app/pages/social-recovery-show-share/social-recovery-show-share.page.ts"]
  E695["src/app/pages/social-recovery-validate-share/social-recovery-validate-share.module.ts"]
  E696["src/app/pages/social-recovery-validate-share/social-recovery-validate-share.page.html"]
  E697["src/app/pages/social-recovery-validate-share/social-recovery-validate-share.page.scss"]
  E698["src/app/pages/social-recovery-validate-share/social-recovery-validate-share.page.spec.ts"]
  E699["src/app/pages/social-recovery-validate-share/social-recovery-validate-share.page.ts"]
  E700["src/app/pages/tab-scan/tab-scan.module.ts"]
  E701["src/app/pages/tab-scan/tab-scan.page.html"]
  E702["src/app/pages/tab-scan/tab-scan.page.scss"]
  E703["src/app/pages/tab-scan/tab-scan.page.spec.ts"]
  E704["src/app/pages/tab-scan/tab-scan.page.ts"]
  E705["src/app/pages/tab-secrets/tab-secret-popover/tab-secret-popover.component.html"]
  E706["src/app/pages/tab-secrets/tab-secret-popover/tab-secret-popover.component.scss"]
  E707["src/app/pages/tab-secrets/tab-secret-popover/tab-secret-popover.component.spec.ts"]
  E708["src/app/pages/tab-secrets/tab-secret-popover/tab-secret-popover.component.ts"]
  E709["src/app/pages/tab-secrets/tab-secrets-routing.module.ts"]
  E710["src/app/pages/tab-secrets/tab-secrets.module.ts"]
  E711["src/app/pages/tab-secrets/tab-secrets.page.html"]
  E712["src/app/pages/tab-secrets/tab-secrets.page.scss"]
  E713["src/app/pages/tab-secrets/tab-secrets.page.spec.ts"]
  E714["src/app/pages/tab-secrets/tab-secrets.page.ts"]
  E715["src/app/pages/tab-settings/tab-settings.module.ts"]
  E716["src/app/pages/tab-settings/tab-settings.page.html"]
  E717["src/app/pages/tab-settings/tab-settings.page.scss"]
  E718["src/app/pages/tab-settings/tab-settings.page.spec.ts"]
  E719["src/app/pages/tab-settings/tab-settings.page.ts"]
  E720["src/app/pages/tabs/tabs.module.ts"]
  E721["src/app/pages/tabs/tabs.page.html"]
  E722["src/app/pages/tabs/tabs.page.scss"]
  E723["src/app/pages/tabs/tabs.page.spec.ts"]
  E724["src/app/pages/tabs/tabs.page.ts"]
  E725["src/app/pages/tabs/tabs.router.module.ts"]
  E726["src/app/pages/transaction-signed/transaction-signed.module.ts"]
  E727["src/app/pages/transaction-signed/transaction-signed.page.html"]
  E728["src/app/pages/transaction-signed/transaction-signed.page.scss"]
  E729["src/app/pages/transaction-signed/transaction-signed.page.spec.ts"]
  E730["src/app/pages/transaction-signed/transaction-signed.page.ts"]
  E731["src/app/pages/vault-interaction-settings/vault-interaction-settings.module.ts"]
  E732["src/app/pages/vault-interaction-settings/vault-interaction-settings.page.html"]
  E733["src/app/pages/vault-interaction-settings/vault-interaction-settings.page.scss"]
  E734["src/app/pages/vault-interaction-settings/vault-interaction-settings.page.spec.ts"]
  E735["src/app/pages/vault-interaction-settings/vault-interaction-settings.page.ts"]
  E736["src/app/pages/warning-modal/warning-modal.module.ts"]
  E737["src/app/pages/warning-modal/warning-modal.page.html"]
  E738["src/app/pages/warning-modal/warning-modal.page.scss"]
  E739["src/app/pages/warning-modal/warning-modal.page.spec.ts"]
  E740["src/app/pages/warning-modal/warning-modal.page.ts"]
  E741["src/app/pages/wordlist/wordlist-routing.module.ts"]
  E742["src/app/pages/wordlist/wordlist.module.ts"]
  E743["src/app/pages/wordlist/wordlist.page.html"]
  E744["src/app/pages/wordlist/wordlist.page.scss"]
  E745["src/app/pages/wordlist/wordlist.page.spec.ts"]
  E746["src/app/pages/wordlist/wordlist.page.ts"]
  E747["src/app/pipes/pipes.module.ts"]
  E748["src/app/pipes/secret-filter/secret-filter.pipe.spec.ts"]
  E749["src/app/pipes/secret-filter/secret-filter.pipe.ts"]
  E750["src/app/pipes/wallet-status/wallet-status.pipe.spec.ts"]
  E751["src/app/pipes/wallet-status/wallet-status.pipe.ts"]
  E752["src/app/services/audio/audio.browser.service.ts"]
  E753["src/app/services/audio/audio.factory.ts"]
  E754["src/app/services/audio/audio.native.servive.ts"]
  E755["src/app/services/camera/camera.browser.service.ts"]
  E756["src/app/services/camera/camera.factory.ts"]
  E757["src/app/services/camera/camera.native.service.spec.ts"]
  E758["src/app/services/camera/camera.native.service.ts"]
  E759["src/app/services/coin-flip/coin-flip.service.spec.ts"]
  E760["src/app/services/coin-flip/coin-flip.service.ts"]
  E761["src/app/services/contacts/contacts.service.spec.ts"]
  E762["src/app/services/contacts/contacts.service.ts"]
  E763["src/app/services/device/device.service.spec.ts"]
  E764["src/app/services/device/device.service.ts"]
  E765["src/app/services/dice-roll/dice-roll.service.spec.ts"]
  E766["src/app/services/dice-roll/dice-roll.service.ts"]
  E767["src/app/services/entropy/IEntropyGenerator.ts"]
  E768["src/app/services/entropy/dummy.entropy.service.ts"]
  E769["src/app/services/entropy/entropy.service.spec.ts"]
  E770["src/app/services/entropy/entropy.service.ts"]
  E771["src/app/services/environment/vault-environment.service.ts"]
  E772["src/app/services/error-handler/error-handler.service.spec.ts"]
  E773["src/app/services/error-handler/error-handler.service.ts"]
  E774["src/app/services/gyroscope/gyroscope.factory.ts"]
  E775["src/app/services/gyroscope/gyroscope.native.service.ts"]
  E776["src/app/services/gyroscope/gyroscope.service.spec.ts"]
  E777["src/app/services/iac/iac.service.spec.ts"]
  E778["src/app/services/iac/iac.service.ts"]
  E779["src/app/services/interaction/interaction.service.spec.ts"]
  E780["src/app/services/interaction/interaction.service.ts"]
  E781["src/app/services/lifehash/lifehash.service.spec.ts"]
  E782["src/app/services/lifehash/lifehash.service.ts"]
  E783["src/app/services/migration/migration.service.ts"]
  E784["src/app/services/mode/mode.service.spec.ts"]
  E785["src/app/services/mode/mode.service.ts"]
  E786["src/app/services/mode/strategy/ModeStrategy.ts"]
  E787["src/app/services/mode/strategy/advanced-mode.service.ts"]
  E788["src/app/services/mode/strategy/basic-mode.service.ts"]
  E789["src/app/services/modules/modules.service.ts"]
  E790["src/app/services/navigation/navigation.service.spec.ts"]
  E791["src/app/services/navigation/navigation.service.ts"]
  E792["src/app/services/sapling-native/sapling-native.service.ts"]
  E793["src/app/services/secrets/secrets.service.spec.ts"]
  E794["src/app/services/secrets/secrets.service.ts"]
  E795["src/app/services/secure-storage/secure-storage.factory.ts"]
  E796["src/app/services/secure-storage/secure-storage.mock.ts"]
  E797["src/app/services/secure-storage/secure-storage.service.spec.ts"]
  E798["src/app/services/secure-storage/secure-storage.service.ts"]
  E799["src/app/services/share-url/share-url.service.spec.ts"]
  E800["src/app/services/share-url/share-url.service.ts"]
  E801["src/app/services/solflare-keystone/solflare-keystone.service.spec.ts"]
  E802["src/app/services/solflare-keystone/solflare-keystone.service.ts"]
  E803["src/app/services/startup-checks/startup-checks.service.spec.ts"]
  E804["src/app/services/startup-checks/startup-checks.service.ts"]
  E805["src/app/services/storage/storage.service.spec.ts"]
  E806["src/app/services/storage/storage.service.ts"]
  E807["src/app/services/token/TokenService.ts"]
  E808["src/app/social-recovery-import-share/social-recovery-import-share.service.ts"]
  E809["src/app/utils/migration.ts"]
  E810["src/app/utils/retry.ts"]
  E811["src/app/utils/utils.ts"]
  E812["src/app/validators/mnemonic.validator.ts"]
  E813["src/assets/i18n/de.json"]
  E814["src/assets/i18n/en.json"]
  E815["src/assets/i18n/es.json"]
  E816["src/assets/i18n/fr.json"]
  E817["src/assets/i18n/pt_BR.json"]
  E818["src/assets/i18n/ru.json"]
  E819["src/assets/i18n/zh_CN.json"]
  E820["src/assets/icon/favicon.png"]
  E821["src/assets/icons/extension-puzzle.svg"]
  E822["src/assets/icons/md-check.svg"]
  E823["src/assets/icons/md-edit.svg"]
  E824["src/assets/icons/md-fiber_manual_record.svg"]
  E825["src/assets/icons/md-fiber_pin.svg"]
  E826["src/assets/icons/md-group_work.svg"]
  E827["src/assets/icons/md-info.svg"]
  E828["src/assets/icons/md-mic.svg"]
  E829["src/assets/icons/md-people.svg"]
  E830["src/assets/icons/md-screen_rotation.svg"]
  E831["src/assets/icons/md-swap_horiz.svg"]
  E832["src/assets/icons/md-touch_app.svg"]
  E833["src/assets/icons/md-vertical_align_bottom.svg"]
  E834["src/assets/icons/md-videocam.svg"]
  E835["src/assets/icons/md-warning.svg"]
  E836["src/assets/icons/shapes.svg"]
  E837["src/assets/icons/shield-checkmark.svg"]
  E838["src/assets/img/2-apps-split.svg"]
  E839["src/assets/img/AirGap_Onboarding_Wallet.svg"]
  E840["src/assets/img/app-switching.svg"]
  E841["src/assets/img/clone.svg"]
  E842["src/assets/img/companion-apps.svg"]
  E843["src/assets/img/local_authentication_onboarding.svg"]
  E844["src/assets/img/logo.svg"]
  E845["src/assets/img/network_connection.svg"]
  E846["src/assets/img/no-wallet-added-onboarding.svg"]
  E847["src/assets/img/onboarding-advanced.svg"]
  E848["src/assets/img/onboarding-backup-seed-phrase.svg"]
  E849["src/assets/img/onboarding-offline.svg"]
  E850["src/assets/img/onboarding-peace-of-mind.svg"]
  E851["src/assets/img/onboarding-terms.svg"]
  E852["src/assets/img/onboarding-watch-only.svg"]
  E853["src/assets/img/permission_onboarding.svg"]
  E854["src/assets/img/permission_onboarding_camera.svg"]
  E855["src/assets/img/qr_code_guides.svg"]
  E856["src/assets/img/qrcode.svg"]
  E857["src/assets/img/root_detection.svg"]
  E858["src/assets/img/scan_confirmation_onboarding.svg"]
  E859["src/assets/img/screenshot_detected.svg"]
  E860["src/assets/img/send-one-device.svg"]
  E861["src/assets/img/send-two-device.svg"]
  E862["src/assets/img/shop.png"]
  E863["src/assets/img/social-group.svg"]
  E864["src/assets/img/social-group.xsd"]
  E865["src/assets/js/error-check.js"]
  E866["src/assets/logos/airgap-wallet-app-logo.png"]
  E867["src/assets/logos/airgap-wallet-app-logo.svg"]
  E868["src/assets/logos/bluewallet.png"]
  E869["src/assets/logos/imtoken-wallet.svg"]
  E870["src/assets/logos/metamask.webp"]
  E871["src/assets/logos/nunchuk.png"]
  E872["src/assets/logos/rabby-wallet.svg"]
  E873["src/assets/logos/sparrowwallet.png"]
  E874["src/assets/logos/specterwallet.png"]
  E875["src/assets/logos/superhero-wallet.png"]
  E876["src/assets/sapling/sapling-output.params"]
  E877["src/assets/sapling/sapling-spend.params"]
  E878["src/assets/workers/entropyCalculatorWorker.ts"]
  E879["src/assets/workers/hashWorker.ts"]
  E880["src/assets/workers/sha3.min.js"]
  E881["src/environments/environment.prod.ts"]
  E882["src/environments/environment.ts"]
  E883["src/global.scss"]
  E884["src/index.html"]
  E885["src/karma.conf.js"]
  E886["src/main.ts"]
  E887["src/manifest.webmanifest"]
  E888["src/polyfills.ts"]
  E889["src/test.ts"]
  E890["src/theme/variables.scss"]
  E891["src/tsconfig.app.json"]
  E892["src/tsconfig.spec.json"]
  E893["src/tslint.json"]
  E894["src/zone-flags.ts"]
  E895["test-config/ionic-mocks.ts"]
  E896["test-config/plugins-mocks.ts"]
  E897["test-config/storage-mock.ts"]
  E898["test-config/unit-test-helper.ts"]
  E899["test-config/wallet-mock.ts"]
  E900["tsconfig.json"]
  E901["tslint.json"]
  E902["uitest/README.md"]
  E903["uitest/config.json"]
  E904["uitest/pom.xml"]
  E905["uitest/src/main/resources/log4j.properties"]
  E906["uitest/src/test/java/Enums/TestResultStatus.java"]
  E907["uitest/src/test/java/Helpers/Config.java"]
  E908["uitest/src/test/java/Helpers/Log.java"]
  E909["uitest/src/test/java/Helpers/SleepExtension.java"]
  E910["uitest/src/test/java/Helpers/TakeScreenExtension.java"]
  E911["uitest/src/test/java/Helpers/TestResultLoggerExtension.java"]
  E912["uitest/src/test/java/Pages/AccountAdressPage.java"]
  E913["uitest/src/test/java/Pages/AddAccountPage.java"]
  E914["uitest/src/test/java/Pages/BasePage.java"]
  E915["uitest/src/test/java/Pages/MainPage.java"]
  E916["uitest/src/test/java/Pages/SaveSecretPage.java"]
  E917["uitest/src/test/java/Pages/Settings/EditSecretPage.java"]
  E918["uitest/src/test/java/Pages/Settings/SettingPage.java"]
  E919["uitest/src/test/java/Pages/Settings/SocialRevoveryPage.java"]
  E920["uitest/src/test/java/Pages/Welcome/DisclaimerPage.java"]
  E921["uitest/src/test/java/Pages/Welcome/GenerateSecretPage.java"]
  E922["uitest/src/test/java/Pages/Welcome/ImportPage.java"]
  E923["uitest/src/test/java/Pages/Welcome/SelectSecurityPage.java"]
  E924["uitest/src/test/java/Pages/Welcome/SetUpPage.java"]
  E925["uitest/src/test/java/TestFixtures/BaseTestFixture.java"]
  E926["uitest/src/test/java/Tests/GenerateSecretTest.java"]
  E927["uitest/src/test/java/Tests/ImportSecretTest.java"]
  E928["uitest/src/test/java/Tests/MultiAccountsTest.java"]
  E929["uitest/src/test/java/Tests/ParanoiaModeTest.java"]
  E930["uitest/src/test/java/Tests/SocialRecoveryTest.java.bak"]
  E931["yarn.lock"]
  E932["scripts/airgap-vault-kaizou-nonregression.js"]
  E933["scripts/airgap-vault-kaizou-karma.conf.js"]
  E934["scripts/airgap-vault-kaizou-karma-gate.js"]
  E935["contratos/airgap-vault-kaizou-v6-readme.md"]
  E936["contratos/airgap-vault-kaizou-solana-release.schema.json"]
  E937["src/app/pages/deserialized-detail/deserialized-detail.effects.spec.ts"]
  E938["scripts/airgap-vault-kaizou-build-release-with-solana-module.js"]
  E939["scripts/airgap-vault-kaizou-solana-signing-simulation.js"]
  E940["logs/U18-2026-08-24-solana-signing-simulation.log"]
  E941["scripts/airgap-vault-kaizou-solflare-capture-resilience-simulation.js"]
  E942["logs/U23-2026-08-24-solflare-capture-resilience.log"]
  E943["logs/R03-2026-08-24-wallet-pool-stake-homologation.log"]
