graph TD
  E1[".browserslistrc"]:::livre
  E2[".devcontainer/Dockerfile"]:::livre
  E3[".devcontainer/devcontainer.json"]:::livre
  E4[".dockerignore"]:::livre
  E5[".github/workflows/build.yml"]:::livre
  E6[".github/workflows/netflify.yml"]:::livre
  E7[".gitignore"]:::livre
  E8[".gitlab-ci.yml"]:::livre
  E9[".gitlab/issue_templates/Bug.md"]:::livre
  E10[".gitlab/issue_templates/Epic.md"]:::livre
  E11[".gitlab/issue_templates/Feature.md"]:::livre
  E12[".gitlab/issue_templates/Task.md"]:::livre
  E13[".gitlab/issue_templates/TestChecklist.md"]:::livre
  E14[".gitlab/issue_templates/user_report.md"]:::livre
  E15[".husky/pre-commit"]:::livre
  E16[".prettierignore"]:::livre
  E17[".prettierrc"]:::livre
  E18[".tx/config"]:::livre
  E19["Dockerfile"]:::livre
  E20["LICENSE.md"]:::livre
  E21["README.md"]:::livre
  E22["android/.gitignore"]:::livre
  E23["android/.project"]:::livre
  E24["android/.settings/org.eclipse.buildship.core.prefs"]:::livre
  E25["android/app/.npmignore"]:::livre
  E26["android/app/build.gradle"]:::livre
  E27["android/app/capacitor.build.gradle"]:::livre
  E28["android/app/proguard-rules.pro"]:::livre
  E29["android/app/src/androidTest/java/com/getcapacitor/myapp/ExampleInstrumentedTest.java"]:::livre
  E30["android/app/src/main/AndroidManifest.xml"]:::livre
  E31["android/app/src/main/assets/capacitor.config.json"]:::livre
  E32["android/app/src/main/assets/capacitor.plugins.json"]:::livre
  E33["android/app/src/main/java/it/airgap/vault/MainActivity.java"]:::livre
  E34["android/app/src/main/java/it/airgap/vault/plugin/PluginError.kt"]:::livre
  E35["android/app/src/main/java/it/airgap/vault/plugin/appinfo/AppInfo.kt"]:::livre
  E36["android/app/src/main/java/it/airgap/vault/plugin/camerapreview/CameraFragment.java"]:::livre
  E37["android/app/src/main/java/it/airgap/vault/plugin/camerapreview/CameraPreview.kt"]:::livre
  E38["android/app/src/main/java/it/airgap/vault/plugin/camerapreview/CustomSurfaceView.java"]:::livre
  E39["android/app/src/main/java/it/airgap/vault/plugin/camerapreview/Preview.java"]:::livre
  E40["android/app/src/main/java/it/airgap/vault/plugin/camerapreview/TapGestureDetector.java"]:::livre
  E41["android/app/src/main/java/it/airgap/vault/plugin/environment/Environment.kt"]:::livre
  E42["android/app/src/main/java/it/airgap/vault/plugin/isolatedmodules/FileExplorer.kt"]:::livre
  E43["android/app/src/main/java/it/airgap/vault/plugin/isolatedmodules/IsolatedModules.kt"]:::livre
  E44["android/app/src/main/java/it/airgap/vault/plugin/isolatedmodules/js/JSEvaluator.kt"]:::livre
  E45["android/app/src/main/java/it/airgap/vault/plugin/isolatedmodules/js/JSModule.kt"]:::livre
  E46["android/app/src/main/java/it/airgap/vault/plugin/isolatedmodules/js/environment/JSEnvironment.kt"]:::livre
  E47["android/app/src/main/java/it/airgap/vault/plugin/isolatedmodules/js/environment/JavaScriptEngineEnvironment.kt"]:::livre
  E48["android/app/src/main/java/it/airgap/vault/plugin/isolatedmodules/js/environment/WebViewEnvironment.kt"]:::livre
  E49["android/app/src/main/java/it/airgap/vault/plugin/saplingnative/SaplingNative.kt"]:::livre
  E50["android/app/src/main/java/it/airgap/vault/plugin/securityutils/AuthOrigin.kt"]:::livre
  E51["android/app/src/main/java/it/airgap/vault/plugin/securityutils/SecurityUtils.kt"]:::livre
  E52["android/app/src/main/java/it/airgap/vault/plugin/securityutils/authprompt/AuthPromptFragment.kt"]:::livre
  E53["android/app/src/main/java/it/airgap/vault/plugin/securityutils/storage/Constants.kt"]:::livre
  E54["android/app/src/main/java/it/airgap/vault/plugin/securityutils/storage/Errors.kt"]:::livre
  E55["android/app/src/main/java/it/airgap/vault/plugin/securityutils/storage/SecureFile.kt"]:::livre
  E56["android/app/src/main/java/it/airgap/vault/plugin/securityutils/storage/SecureFileStorage.kt"]:::livre
  E57["android/app/src/main/java/it/airgap/vault/plugin/securityutils/storage/Storage.kt"]:::livre
  E58["android/app/src/main/java/it/airgap/vault/plugin/zip/Zip.kt"]:::livre
  E59["android/app/src/main/java/it/airgap/vault/util/AnyExtensions.kt"]:::livre
  E60["android/app/src/main/java/it/airgap/vault/util/Assets.kt"]:::livre
  E61["android/app/src/main/java/it/airgap/vault/util/CollectionExtensions.kt"]:::livre
  E62["android/app/src/main/java/it/airgap/vault/util/Deferred.kt"]:::livre
  E63["android/app/src/main/java/it/airgap/vault/util/Filesystem.kt"]:::livre
  E64["android/app/src/main/java/it/airgap/vault/util/Hex.kt"]:::livre
  E65["android/app/src/main/java/it/airgap/vault/util/Interfaces.kt"]:::livre
  E66["android/app/src/main/java/it/airgap/vault/util/JS.kt"]:::livre
  E67["android/app/src/main/java/it/airgap/vault/util/JSExtensions.kt"]:::livre
  E68["android/app/src/main/java/it/airgap/vault/util/PluginExtensions.kt"]:::livre
  E69["android/app/src/main/java/it/airgap/vault/util/StringExtensions.kt"]:::livre
  E70["android/app/src/main/java/it/airgap/vault/util/ViewExtensions.kt"]:::livre
  E71["android/app/src/main/java/it/airgap/vault/util/WebViewExtensions.kt"]:::livre
  E72["android/app/src/main/res/drawable-night/splash_icon.xml"]:::livre
  E73["android/app/src/main/res/drawable/all_overlay.xml"]:::livre
  E74["android/app/src/main/res/drawable/splash_icon.xml"]:::livre
  E75["android/app/src/main/res/layout/activity_main.xml"]:::livre
  E76["android/app/src/main/res/layout/alert_input_dialog.xml"]:::livre
  E77["android/app/src/main/res/layout/alert_setup_dialog.xml"]:::livre
  E78["android/app/src/main/res/layout/fragment_authenticator.xml"]:::livre
  E79["android/app/src/main/res/layout/fragment_camera.xml"]:::livre
  E80["android/app/src/main/res/mipmap-hdpi/ic_launcher.png"]:::livre
  E81["android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png"]:::livre
  E82["android/app/src/main/res/mipmap-ldpi/ic_launcher.png"]:::livre
  E83["android/app/src/main/res/mipmap-ldpi/ic_launcher_round.png"]:::livre
  E84["android/app/src/main/res/mipmap-mdpi/ic_launcher.png"]:::livre
  E85["android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png"]:::livre
  E86["android/app/src/main/res/mipmap-xhdpi/ic_launcher.png"]:::livre
  E87["android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png"]:::livre
  E88["android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png"]:::livre
  E89["android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png"]:::livre
  E90["android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png"]:::livre
  E91["android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png"]:::livre
  E92["android/app/src/main/res/values-night/colors.xml"]:::livre
  E93["android/app/src/main/res/values/colors.xml"]:::livre
  E94["android/app/src/main/res/values/ic_launcher_background.xml"]:::livre
  E95["android/app/src/main/res/values/ids.xml"]:::livre
  E96["android/app/src/main/res/values/strings.xml"]:::livre
  E97["android/app/src/main/res/values/styles.xml"]:::livre
  E98["android/app/src/main/res/xml/config.xml"]:::livre
  E99["android/app/src/main/res/xml/file_paths.xml"]:::livre
  E100["android/app/src/main/res/xml/network_security_config.xml"]:::livre
  E101["android/app/src/test/java/com/getcapacitor/myapp/ExampleUnitTest.java"]:::livre
  E102["android/build.gradle"]:::livre
  E103["android/capacitor.settings.gradle"]:::livre
  E104["android/gradle.properties"]:::livre
  E105["android/gradle/wrapper/gradle-wrapper.jar"]:::livre
  E106["android/gradle/wrapper/gradle-wrapper.properties"]:::livre
  E107["android/gradlew"]:::livre
  E108["android/gradlew.bat"]:::livre
  E109["android/settings.gradle"]:::livre
  E110["android/variables.gradle"]:::livre
  E111["angular.json"]:::livre
  E112["apple/apple-app-site-association"]:::livre
  E113["apply-diagnostic-modules.js"]:::livre
  E114["banner.png"]:::livre
  E115["build/android/Dockerfile"]:::livre
  E116["build/android/debug.keystore"]:::livre
  E117["capacitor.config.ts"]:::livre
  E118["competencias.yaml"]:::bloqueado
  E119["contratos/solflare-keystone.schema.json"]:::bloqueado
  E120["copy-builtin-modules.js"]:::livre
  E121["devices.png"]:::livre
  E122["docs/airgap-vault-kaizou-competences.mmd"]:::bloqueado
  E123["docs/airgap-vault-kaizou-concurrency.mmd"]:::bloqueado
  E124["docs/airgap-vault-kaizou-dependencies.mmd"]:::bloqueado
  E125["docs/airgap-vault-kaizou-flow.mmd"]:::bloqueado
  E126["docs/airgap-vault-kaizou-modules.mmd"]:::bloqueado
  E127["docs/airgap-vault-kaizou-progress.mmd"]:::bloqueado
  E128["e2e/protractor.conf.js"]:::livre
  E129["e2e/src/app.e2e-spec.ts"]:::livre
  E130["e2e/src/app.po.ts"]:::livre
  E131["e2e/tsconfig.e2e.json"]:::livre
  E132["electron/.gitignore"]:::livre
  E133["electron/capacitor.config.json"]:::livre
  E134["electron/index.js"]:::livre
  E135["electron/main.js"]:::livre
  E136["electron/package-lock.json"]:::livre
  E137["electron/package.json"]:::livre
  E138["electron/resources/entitlements.mac.plist"]:::livre
  E139["electron/resources/icons/icon.png"]:::livre
  E140["electron/splash_assets/splash.png"]:::livre
  E141["estado.md"]:::bloqueado
  E142["fastlane/metadata/android/en-US/full_description.txt"]:::livre
  E143["fastlane/metadata/android/en-US/images/icon.png"]:::livre
  E144["fastlane/metadata/android/en-US/images/phoneScreenshots/1.png"]:::livre
  E145["fastlane/metadata/android/en-US/images/phoneScreenshots/2.png"]:::livre
  E146["fastlane/metadata/android/en-US/images/phoneScreenshots/3.png"]:::livre
  E147["fastlane/metadata/android/en-US/images/phoneScreenshots/4.png"]:::livre
  E148["fastlane/metadata/android/en-US/images/phoneScreenshots/5.png"]:::livre
  E149["fastlane/metadata/android/en-US/images/phoneScreenshots/6.png"]:::livre
  E150["fastlane/metadata/android/en-US/short_description.txt"]:::livre
  E151["fastlane/metadata/android/en-US/title.txt"]:::livre
  E152["fastlane/metadata/android/en-US/video.txt"]:::livre
  E153["fix-qrscanner-gradle.js"]:::livre
  E154["icons/icon-128.webp"]:::livre
  E155["icons/icon-192.webp"]:::livre
  E156["icons/icon-256.webp"]:::livre
  E157["icons/icon-512.webp"]:::livre
  E158["icons/icon-72.webp"]:::livre
  E159["icons/icon-96.webp"]:::livre
  E160["install-build-deps.js"]:::livre
  E161["install-test-deps.js"]:::livre
  E162["ionic.config.json"]:::livre
  E163["ios/.gitignore"]:::livre
  E164["ios/App/App.xcodeproj/project.pbxproj"]:::livre
  E165["ios/App/App.xcodeproj/project.xcworkspace/contents.xcworkspacedata"]:::livre
  E166["ios/App/App.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist"]:::livre
  E167["ios/App/App.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved"]:::livre
  E168["ios/App/App.xcodeproj/xcshareddata/xcschemes/App.xcscheme"]:::livre
  E169["ios/App/App.xcworkspace/contents.xcworkspacedata"]:::livre
  E170["ios/App/App.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist"]:::livre
  E171["ios/App/App.xcworkspace/xcshareddata/swiftpm/Package.resolved"]:::livre
  E172["ios/App/App.xcworkspace/xcshareddata/swiftpm/configuration/Package.resolved"]:::livre
  E173["ios/App/App/App-Bridging-Header.h"]:::livre
  E174["ios/App/App/AppDelegate.swift"]:::livre
  E175["ios/App/App/AppInfo/AppInfo.m"]:::livre
  E176["ios/App/App/AppInfo/AppInfo.swift"]:::livre
  E177["ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-512@2x.png"]:::livre
  E178["ios/App/App/Assets.xcassets/AppIcon.appiconset/Contents.json"]:::livre
  E179["ios/App/App/Assets.xcassets/Contents.json"]:::livre
  E180["ios/App/App/Assets.xcassets/Splash.imageset/Contents.json"]:::livre
  E181["ios/App/App/Assets.xcassets/Splash.imageset/Default@1x~universal~anyany-dark.png"]:::livre
  E182["ios/App/App/Assets.xcassets/Splash.imageset/Default@1x~universal~anyany.png"]:::livre
  E183["ios/App/App/Assets.xcassets/Splash.imageset/Default@2x~universal~anyany-dark.png"]:::livre
  E184["ios/App/App/Assets.xcassets/Splash.imageset/Default@2x~universal~anyany.png"]:::livre
  E185["ios/App/App/Assets.xcassets/Splash.imageset/Default@3x~universal~anyany-dark.png"]:::livre
  E186["ios/App/App/Assets.xcassets/Splash.imageset/Default@3x~universal~anyany.png"]:::livre
  E187["ios/App/App/Base.lproj/LaunchScreen.storyboard"]:::livre
  E188["ios/App/App/Base.lproj/Main.storyboard"]:::livre
  E189["ios/App/App/Camera/CameraController.swift"]:::livre
  E190["ios/App/App/Camera/CameraPreview.m"]:::livre
  E191["ios/App/App/Camera/CameraPreview.swift"]:::livre
  E192["ios/App/App/Environment/Environment.m"]:::livre
  E193["ios/App/App/Environment/Environment.swift"]:::livre
  E194["ios/App/App/Helpers/Extensions/Dictionary+Additions.swift"]:::livre
  E195["ios/App/App/Helpers/Extensions/JSValue+Additions.swift"]:::livre
  E196["ios/App/App/Helpers/Extensions/PluginCall+Additions.swift"]:::livre
  E197["ios/App/App/Helpers/Extensions/Sequence+Additions.swift"]:::livre
  E198["ios/App/App/Helpers/Extensions/WK+Additions.swift"]:::livre
  E199["ios/App/App/Helpers/Filesystem.swift"]:::livre
  E200["ios/App/App/Helpers/Hex.swift"]:::livre
  E201["ios/App/App/Helpers/JS.swift"]:::livre
  E202["ios/App/App/Info.plist"]:::livre
  E203["ios/App/App/IsolatedModules/FileExplorer.swift"]:::livre
  E204["ios/App/App/IsolatedModules/IsolatedModules.m"]:::livre
  E205["ios/App/App/IsolatedModules/IsolatedModules.swift"]:::livre
  E206["ios/App/App/IsolatedModules/JS/Environment/JSEnvironment.swift"]:::livre
  E207["ios/App/App/IsolatedModules/JS/Environment/WebViewEnvironment.swift"]:::livre
  E208["ios/App/App/IsolatedModules/JS/JSEvaluator.swift"]:::livre
  E209["ios/App/App/IsolatedModules/JS/JSModule.swift"]:::livre
  E210["ios/App/App/IsolatedModules/ModuleManifest.swift"]:::livre
  E211["ios/App/App/SaplingNative/SaplingNative.m"]:::livre
  E212["ios/App/App/SaplingNative/SaplingNative.swift"]:::livre
  E213["ios/App/App/SecurityUtils/DeviceIntegrity.swift"]:::livre
  E214["ios/App/App/SecurityUtils/Keychain.swift"]:::livre
  E215["ios/App/App/SecurityUtils/LocalAuthentication.swift"]:::livre
  E216["ios/App/App/SecurityUtils/SecureScreen.swift"]:::livre
  E217["ios/App/App/SecurityUtils/SecureStorage.swift"]:::livre
  E218["ios/App/App/SecurityUtils/SecurityUtils.m"]:::livre
  E219["ios/App/App/SecurityUtils/SecurityUtils.swift"]:::livre
  E220["ios/App/App/SecurityUtils/VaultError.swift"]:::livre
  E221["ios/App/App/ViewController.swift"]:::livre
  E222["ios/App/App/Zip/Zip.m"]:::livre
  E223["ios/App/App/Zip/Zip.swift"]:::livre
  E224["ios/App/App/capacitor.config.json"]:::livre
  E225["ios/App/App/config.xml"]:::livre
  E226["ios/App/Podfile"]:::livre
  E227["ios/App/Podfile.lock"]:::livre
  E228["lexico.yaml"]:::bloqueado
  E229["manifesto.yaml"]:::bloqueado
  E230["ngcc.config.js"]:::livre
  E231["package.json"]:::bloqueado
  E232["patch-dependency-versions.js"]:::livre
  E233["resources/logo-dark_splash.svg"]:::livre
  E234["resources/logo.svg"]:::livre
  E235["resources/logo_splash.svg"]:::livre
  E236["resources/splash-dark.svg"]:::livre
  E237["resources/splash.svg"]:::livre
  E238["script.ts"]:::livre
  E239["scripts/airgap-vault-kaizou-generate-diagrams.py"]:::bloqueado
  E240["scripts/airgap-vault-kaizou-verify-structure.py"]:::bloqueado
  E241["src/app/app-routing.module.ts"]:::livre
  E242["src/app/app.component.html"]:::livre
  E243["src/app/app.component.spec.ts"]:::livre
  E244["src/app/app.component.ts"]:::livre
  E245["src/app/app.module.ts"]:::livre
  E246["src/app/app.reducers.ts"]:::livre
  E247["src/app/app.scss"]:::livre
  E248["src/app/capacitor-plugins/definitions.ts"]:::livre
  E249["src/app/capacitor-plugins/injection-tokens.ts"]:::livre
  E250["src/app/components/add-address/add-address.component.html"]:::livre
  E251["src/app/components/add-address/add-address.component.scss"]:::livre
  E252["src/app/components/add-address/add-address.component.spec.ts"]:::livre
  E253["src/app/components/add-address/add-address.component.ts"]:::livre
  E254["src/app/components/components.module.ts"]:::livre
  E255["src/app/components/entropy-progress/entropy-progress.component.html"]:::livre
  E256["src/app/components/entropy-progress/entropy-progress.component.scss"]:::livre
  E257["src/app/components/entropy-progress/entropy-progress.component.spec.ts"]:::livre
  E258["src/app/components/entropy-progress/entropy-progress.component.ts"]:::livre
  E259["src/app/components/grid-input/grid-input.component.html"]:::livre
  E260["src/app/components/grid-input/grid-input.component.scss"]:::livre
  E261["src/app/components/grid-input/grid-input.component.spec.ts"]:::livre
  E262["src/app/components/grid-input/grid-input.component.ts"]:::livre
  E263["src/app/components/interaction-selection/interaction-selection.component.html"]:::livre
  E264["src/app/components/interaction-selection/interaction-selection.component.scss"]:::livre
  E265["src/app/components/interaction-selection/interaction-selection.component.spec.ts"]:::livre
  E266["src/app/components/interaction-selection/interaction-selection.component.ts"]:::livre
  E267["src/app/components/keyboard-popover/keyboard-popover.component.html"]:::livre
  E268["src/app/components/keyboard-popover/keyboard-popover.component.scss"]:::livre
  E269["src/app/components/keyboard-popover/keyboard-popover.component.spec.ts"]:::livre
  E270["src/app/components/keyboard-popover/keyboard-popover.component.ts"]:::livre
  E271["src/app/components/message-sign-request/message-sign-request.component.html"]:::livre
  E272["src/app/components/message-sign-request/message-sign-request.component.scss"]:::livre
  E273["src/app/components/message-sign-request/message-sign-request.component.spec.ts"]:::livre
  E274["src/app/components/message-sign-request/message-sign-request.component.ts"]:::livre
  E275["src/app/components/message-sign-response/message-sign-response.component.html"]:::livre
  E276["src/app/components/message-sign-response/message-sign-response.component.scss"]:::livre
  E277["src/app/components/message-sign-response/message-sign-response.component.spec.ts"]:::livre
  E278["src/app/components/message-sign-response/message-sign-response.component.ts"]:::livre
  E279["src/app/components/mnemonic-keyboard/mnemonic-keyboard.component.html"]:::livre
  E280["src/app/components/mnemonic-keyboard/mnemonic-keyboard.component.scss"]:::livre
  E281["src/app/components/mnemonic-keyboard/mnemonic-keyboard.component.spec.ts"]:::livre
  E282["src/app/components/mnemonic-keyboard/mnemonic-keyboard.component.ts"]:::livre
  E283["src/app/components/progress-footer/progress-footer.component.html"]:::livre
  E284["src/app/components/progress-footer/progress-footer.component.scss"]:::livre
  E285["src/app/components/progress-footer/progress-footer.component.spec.ts"]:::livre
  E286["src/app/components/progress-footer/progress-footer.component.ts"]:::livre
  E287["src/app/components/progress-indicator/progress-indicator.component.html"]:::livre
  E288["src/app/components/progress-indicator/progress-indicator.component.scss"]:::livre
  E289["src/app/components/progress-indicator/progress-indicator.component.spec.ts"]:::livre
  E290["src/app/components/progress-indicator/progress-indicator.component.ts"]:::livre
  E291["src/app/components/secret-item/secret-item.component.html"]:::livre
  E292["src/app/components/secret-item/secret-item.component.scss"]:::livre
  E293["src/app/components/secret-item/secret-item.component.spec.ts"]:::livre
  E294["src/app/components/secret-item/secret-item.component.ts"]:::livre
  E295["src/app/components/secret-option-item/secret-option-item.component.html"]:::livre
  E296["src/app/components/secret-option-item/secret-option-item.component.scss"]:::livre
  E297["src/app/components/secret-option-item/secret-option-item.component.spec.ts"]:::livre
  E298["src/app/components/secret-option-item/secret-option-item.component.ts"]:::livre
  E299["src/app/components/signed-transaction/signed-transaction.component.html"]:::livre
  E300["src/app/components/signed-transaction/signed-transaction.component.scss"]:::livre
  E301["src/app/components/signed-transaction/signed-transaction.component.spec.ts"]:::livre
  E302["src/app/components/signed-transaction/signed-transaction.component.ts"]:::livre
  E303["src/app/components/touch-entropy/touch-entropy.component.html"]:::livre
  E304["src/app/components/touch-entropy/touch-entropy.component.scss"]:::livre
  E305["src/app/components/touch-entropy/touch-entropy.component.spec.ts"]:::livre
  E306["src/app/components/touch-entropy/touch-entropy.component.ts"]:::livre
  E307["src/app/components/trace-input/trace-input.directive.ts"]:::livre
  E308["src/app/components/transaction-warning/transaction-warning.component.html"]:::livre
  E309["src/app/components/transaction-warning/transaction-warning.component.scss"]:::livre
  E310["src/app/components/transaction-warning/transaction-warning.component.spec.ts"]:::livre
  E311["src/app/components/transaction-warning/transaction-warning.component.ts"]:::livre
  E312["src/app/components/transaction/transaction.component.html"]:::livre
  E313["src/app/components/transaction/transaction.component.scss"]:::livre
  E314["src/app/components/transaction/transaction.component.spec.ts"]:::livre
  E315["src/app/components/transaction/transaction.component.ts"]:::livre
  E316["src/app/components/transaction/transaction.store.ts"]:::livre
  E317["src/app/components/verify-key-alt/verify-key-alt.component.html"]:::livre
  E318["src/app/components/verify-key-alt/verify-key-alt.component.scss"]:::livre
  E319["src/app/components/verify-key-alt/verify-key-alt.component.spec.ts"]:::livre
  E320["src/app/components/verify-key-alt/verify-key-alt.component.ts"]:::livre
  E321["src/app/components/verify-key/verify-key.component.html"]:::livre
  E322["src/app/components/verify-key/verify-key.component.scss"]:::livre
  E323["src/app/components/verify-key/verify-key.component.spec.ts"]:::livre
  E324["src/app/components/verify-key/verify-key.component.ts"]:::livre
  E325["src/app/config/app-config.ts"]:::livre
  E326["src/app/constants/constants.ts"]:::livre
  E327["src/app/functions/exposed-promise.ts"]:::livre
  E328["src/app/models/BIP39Signer.spec.ts"]:::livre
  E329["src/app/models/BIP39Signer.ts"]:::livre
  E330["src/app/models/BIP85.spec.ts"]:::livre
  E331["src/app/models/identifiable.ts"]:::livre
  E332["src/app/models/secret.ts"]:::livre
  E333["src/app/models/sign-transaction-info.ts"]:::livre
  E334["src/app/pages/Installation-type/installation-type.module.ts"]:::livre
  E335["src/app/pages/Installation-type/installation-type.page.html"]:::livre
  E336["src/app/pages/Installation-type/installation-type.page.scss"]:::livre
  E337["src/app/pages/Installation-type/installation-type.page.spec.ts"]:::livre
  E338["src/app/pages/Installation-type/installation-type.page.ts"]:::livre
  E339["src/app/pages/about/about.module.ts"]:::livre
  E340["src/app/pages/about/about.page.html"]:::livre
  E341["src/app/pages/about/about.page.scss"]:::livre
  E342["src/app/pages/about/about.page.spec.ts"]:::livre
  E343["src/app/pages/about/about.page.ts"]:::livre
  E344["src/app/pages/account-add/account-add.module.ts"]:::livre
  E345["src/app/pages/account-add/account-add.page.html"]:::livre
  E346["src/app/pages/account-add/account-add.page.scss"]:::livre
  E347["src/app/pages/account-add/account-add.page.spec.ts"]:::livre
  E348["src/app/pages/account-add/account-add.page.ts"]:::livre
  E349["src/app/pages/account-address/account-address.module.ts"]:::bloqueado
  E350["src/app/pages/account-address/account-address.page.html"]:::bloqueado
  E351["src/app/pages/account-address/account-address.page.scss"]:::bloqueado
  E352["src/app/pages/account-address/account-address.page.spec.ts"]:::bloqueado
  E353["src/app/pages/account-address/account-address.page.ts"]:::bloqueado
  E354["src/app/pages/account-address/account-edit-popover/account-edit-popover.component.html"]:::bloqueado
  E355["src/app/pages/account-address/account-edit-popover/account-edit-popover.component.scss"]:::bloqueado
  E356["src/app/pages/account-address/account-edit-popover/account-edit-popover.component.spec.ts"]:::bloqueado
  E357["src/app/pages/account-address/account-edit-popover/account-edit-popover.component.ts"]:::bloqueado
  E358["src/app/pages/account-share-select/account-share-select-routing.module.ts"]:::livre
  E359["src/app/pages/account-share-select/account-share-select.actions.ts"]:::livre
  E360["src/app/pages/account-share-select/account-share-select.effects.ts"]:::livre
  E361["src/app/pages/account-share-select/account-share-select.module.ts"]:::livre
  E362["src/app/pages/account-share-select/account-share-select.page.html"]:::livre
  E363["src/app/pages/account-share-select/account-share-select.page.scss"]:::livre
  E364["src/app/pages/account-share-select/account-share-select.page.spec.ts"]:::livre
  E365["src/app/pages/account-share-select/account-share-select.page.ts"]:::livre
  E366["src/app/pages/account-share-select/account-share-select.reducers.ts"]:::livre
  E367["src/app/pages/account-share-select/account-share-select.types.ts"]:::livre
  E368["src/app/pages/account-share/account-share.module.ts"]:::bloqueado
  E369["src/app/pages/account-share/account-share.page.html"]:::bloqueado
  E370["src/app/pages/account-share/account-share.page.scss"]:::bloqueado
  E371["src/app/pages/account-share/account-share.page.spec.ts"]:::bloqueado
  E372["src/app/pages/account-share/account-share.page.ts"]:::bloqueado
  E373["src/app/pages/accounts-list/accounts-list-edit-popover/accounts-list-edit-popover.component.html"]:::livre
  E374["src/app/pages/accounts-list/accounts-list-edit-popover/accounts-list-edit-popover.component.scss"]:::livre
  E375["src/app/pages/accounts-list/accounts-list-edit-popover/accounts-list-edit-popover.component.spec.ts"]:::livre
  E376["src/app/pages/accounts-list/accounts-list-edit-popover/accounts-list-edit-popover.component.ts"]:::livre
  E377["src/app/pages/accounts-list/accounts-list-routing.module.ts"]:::livre
  E378["src/app/pages/accounts-list/accounts-list.module.ts"]:::livre
  E379["src/app/pages/accounts-list/accounts-list.page.html"]:::livre
  E380["src/app/pages/accounts-list/accounts-list.page.scss"]:::livre
  E381["src/app/pages/accounts-list/accounts-list.page.spec.ts"]:::livre
  E382["src/app/pages/accounts-list/accounts-list.page.ts"]:::livre
  E383["src/app/pages/address-explorer/address-explorer-routing.module.ts"]:::livre
  E384["src/app/pages/address-explorer/address-explorer.module.ts"]:::livre
  E385["src/app/pages/address-explorer/address-explorer.page.html"]:::livre
  E386["src/app/pages/address-explorer/address-explorer.page.scss"]:::livre
  E387["src/app/pages/address-explorer/address-explorer.page.spec.ts"]:::livre
  E388["src/app/pages/address-explorer/address-explorer.page.ts"]:::livre
  E389["src/app/pages/advanced-mode/advanced-mode.module.ts"]:::livre
  E390["src/app/pages/advanced-mode/advanced-mode.page.html"]:::livre
  E391["src/app/pages/advanced-mode/advanced-mode.page.scss"]:::livre
  E392["src/app/pages/advanced-mode/advanced-mode.page.spec.ts"]:::livre
  E393["src/app/pages/advanced-mode/advanced-mode.page.ts"]:::livre
  E394["src/app/pages/bip85-generate/bip85-generate-routing.module.ts"]:::livre
  E395["src/app/pages/bip85-generate/bip85-generate.module.ts"]:::livre
  E396["src/app/pages/bip85-generate/bip85-generate.page.html"]:::livre
  E397["src/app/pages/bip85-generate/bip85-generate.page.scss"]:::livre
  E398["src/app/pages/bip85-generate/bip85-generate.page.spec.ts"]:::livre
  E399["src/app/pages/bip85-generate/bip85-generate.page.ts"]:::livre
  E400["src/app/pages/bip85-show/bip85-show-routing.module.ts"]:::livre
  E401["src/app/pages/bip85-show/bip85-show.module.ts"]:::livre
  E402["src/app/pages/bip85-show/bip85-show.page.html"]:::livre
  E403["src/app/pages/bip85-show/bip85-show.page.scss"]:::livre
  E404["src/app/pages/bip85-show/bip85-show.page.spec.ts"]:::livre
  E405["src/app/pages/bip85-show/bip85-show.page.ts"]:::livre
  E406["src/app/pages/contact-book-contacts-detail/contact-book-contacts-detail.module.ts"]:::livre
  E407["src/app/pages/contact-book-contacts-detail/contact-book-contacts-detail.page.html"]:::livre
  E408["src/app/pages/contact-book-contacts-detail/contact-book-contacts-detail.page.scss"]:::livre
  E409["src/app/pages/contact-book-contacts-detail/contact-book-contacts-detail.page.spec.ts"]:::livre
  E410["src/app/pages/contact-book-contacts-detail/contact-book-contacts-detail.page.ts"]:::livre
  E411["src/app/pages/contact-book-contacts/contact-book-contacts-item/contact-book-contacts-item.component.html"]:::livre
  E412["src/app/pages/contact-book-contacts/contact-book-contacts-item/contact-book-contacts-item.component.scss"]:::livre
  E413["src/app/pages/contact-book-contacts/contact-book-contacts-item/contact-book-contacts-item.component.ts"]:::livre
  E414["src/app/pages/contact-book-contacts/contact-book-contacts-item/tab-secret-popover.component.spec.ts"]:::livre
  E415["src/app/pages/contact-book-contacts/contact-book-contacts-popover/contact-book-contacts-popover.component.html"]:::livre
  E416["src/app/pages/contact-book-contacts/contact-book-contacts-popover/contact-book-contacts-popover.component.scss"]:::livre
  E417["src/app/pages/contact-book-contacts/contact-book-contacts-popover/contact-book-contacts-popover.component.ts"]:::livre
  E418["src/app/pages/contact-book-contacts/contact-book-contacts-popover/tab-secret-popover.component.spec.ts"]:::livre
  E419["src/app/pages/contact-book-contacts/contact-book-contacts-suggestion/contact-book-contacts-suggestion.component.html"]:::livre
  E420["src/app/pages/contact-book-contacts/contact-book-contacts-suggestion/contact-book-contacts-suggestion.component.scss"]:::livre
  E421["src/app/pages/contact-book-contacts/contact-book-contacts-suggestion/contact-book-contacts-suggestion.component.spec.ts"]:::livre
  E422["src/app/pages/contact-book-contacts/contact-book-contacts-suggestion/contact-book-contacts-suggestion.component.ts"]:::livre
  E423["src/app/pages/contact-book-contacts/contact-book-contacts.module.ts"]:::livre
  E424["src/app/pages/contact-book-contacts/contact-book-contacts.page.html"]:::livre
  E425["src/app/pages/contact-book-contacts/contact-book-contacts.page.scss"]:::livre
  E426["src/app/pages/contact-book-contacts/contact-book-contacts.page.spec.ts"]:::livre
  E427["src/app/pages/contact-book-contacts/contact-book-contacts.page.ts"]:::livre
  E428["src/app/pages/contact-book-onboarding/contact-book-onboarding.module.ts"]:::livre
  E429["src/app/pages/contact-book-onboarding/contact-book-onboarding.page.html"]:::livre
  E430["src/app/pages/contact-book-onboarding/contact-book-onboarding.page.scss"]:::livre
  E431["src/app/pages/contact-book-onboarding/contact-book-onboarding.page.spec.ts"]:::livre
  E432["src/app/pages/contact-book-onboarding/contact-book-onboarding.page.ts"]:::livre
  E433["src/app/pages/contact-book-scan/contact-book-scan.component.html"]:::livre
  E434["src/app/pages/contact-book-scan/contact-book-scan.component.scss"]:::livre
  E435["src/app/pages/contact-book-scan/contact-book-scan.component.spec.ts"]:::livre
  E436["src/app/pages/contact-book-scan/contact-book-scan.module.ts"]:::livre
  E437["src/app/pages/contact-book-scan/contact-book-scan.page.ts"]:::livre
  E438["src/app/pages/contact-book-settings/contact-book-settings.module.ts"]:::livre
  E439["src/app/pages/contact-book-settings/contact-book-settings.page.html"]:::livre
  E440["src/app/pages/contact-book-settings/contact-book-settings.page.scss"]:::livre
  E441["src/app/pages/contact-book-settings/contact-book-settings.page.spec.ts"]:::livre
  E442["src/app/pages/contact-book-settings/contact-book-settings.page.ts"]:::livre
  E443["src/app/pages/deserialized-detail/deserialized-detail.actions.ts"]:::livre
  E444["src/app/pages/deserialized-detail/deserialized-detail.effects.ts"]:::livre
  E445["src/app/pages/deserialized-detail/deserialized-detail.module.ts"]:::livre
  E446["src/app/pages/deserialized-detail/deserialized-detail.page.html"]:::livre
  E447["src/app/pages/deserialized-detail/deserialized-detail.page.scss"]:::livre
  E448["src/app/pages/deserialized-detail/deserialized-detail.page.spec.ts"]:::livre
  E449["src/app/pages/deserialized-detail/deserialized-detail.page.ts"]:::livre
  E450["src/app/pages/deserialized-detail/deserialized-detail.reducer.ts"]:::livre
  E451["src/app/pages/deserialized-detail/deserialized.detail.types.ts"]:::livre
  E452["src/app/pages/distribution-onboarding/distribution-onboarding.module.ts"]:::livre
  E453["src/app/pages/distribution-onboarding/distribution-onboarding.page.html"]:::livre
  E454["src/app/pages/distribution-onboarding/distribution-onboarding.page.scss"]:::livre
  E455["src/app/pages/distribution-onboarding/distribution-onboarding.page.spec.ts"]:::livre
  E456["src/app/pages/distribution-onboarding/distribution-onboarding.page.ts"]:::livre
  E457["src/app/pages/error-history/error-history-routing.module.ts"]:::livre
  E458["src/app/pages/error-history/error-history.module.ts"]:::livre
  E459["src/app/pages/error-history/error-history.page.html"]:::livre
  E460["src/app/pages/error-history/error-history.page.scss"]:::livre
  E461["src/app/pages/error-history/error-history.page.spec.ts"]:::livre
  E462["src/app/pages/error-history/error-history.page.ts"]:::livre
  E463["src/app/pages/interaction-selection-settings/interaction-selection-settings.module.ts"]:::livre
  E464["src/app/pages/interaction-selection-settings/interaction-selection-settings.page.html"]:::livre
  E465["src/app/pages/interaction-selection-settings/interaction-selection-settings.page.scss"]:::livre
  E466["src/app/pages/interaction-selection-settings/interaction-selection-settings.page.spec.ts"]:::livre
  E467["src/app/pages/interaction-selection-settings/interaction-selection-settings.page.ts"]:::livre
  E468["src/app/pages/interaction-selection/interaction-selection.module.ts"]:::livre
  E469["src/app/pages/interaction-selection/interaction-selection.page.html"]:::livre
  E470["src/app/pages/interaction-selection/interaction-selection.page.scss"]:::livre
  E471["src/app/pages/interaction-selection/interaction-selection.page.spec.ts"]:::livre
  E472["src/app/pages/interaction-selection/interaction-selection.page.ts"]:::livre
  E473["src/app/pages/introduction/introduction.module.ts"]:::livre
  E474["src/app/pages/introduction/introduction.page.html"]:::livre
  E475["src/app/pages/introduction/introduction.page.scss"]:::livre
  E476["src/app/pages/introduction/introduction.page.spec.ts"]:::livre
  E477["src/app/pages/introduction/introduction.page.ts"]:::livre
  E478["src/app/pages/isolated-modules-details/isolated-modules-details.module.ts"]:::livre
  E479["src/app/pages/isolated-modules-details/isolated-modules-details.page.html"]:::livre
  E480["src/app/pages/isolated-modules-details/isolated-modules-details.page.scss"]:::livre
  E481["src/app/pages/isolated-modules-details/isolated-modules-details.page.spec.ts"]:::livre
  E482["src/app/pages/isolated-modules-details/isolated-modules-details.page.ts"]:::livre
  E483["src/app/pages/isolated-modules-details/isolated-modules.details.types.ts"]:::livre
  E484["src/app/pages/isolated-modules-details/popover/isolated-modules-details-popover.component.html"]:::livre
  E485["src/app/pages/isolated-modules-details/popover/isolated-modules-details-popover.component.scss"]:::livre
  E486["src/app/pages/isolated-modules-details/popover/isolated-modules-details-popover.component.spec.ts"]:::livre
  E487["src/app/pages/isolated-modules-details/popover/isolated-modules-details-popover.component.ts"]:::livre
  E488["src/app/pages/isolated-modules-list/isolated-modules-list-routing.module.ts"]:::livre
  E489["src/app/pages/isolated-modules-list/isolated-modules-list.module.ts"]:::livre
  E490["src/app/pages/isolated-modules-list/isolated-modules-list.page.html"]:::livre
  E491["src/app/pages/isolated-modules-list/isolated-modules-list.page.scss"]:::livre
  E492["src/app/pages/isolated-modules-list/isolated-modules-list.page.spec.ts"]:::livre
  E493["src/app/pages/isolated-modules-list/isolated-modules-list.page.ts"]:::livre
  E494["src/app/pages/isolated-modules-onboarding/isolated-modules-onboarding.module.ts"]:::livre
  E495["src/app/pages/isolated-modules-onboarding/isolated-modules-onboarding.page.html"]:::livre
  E496["src/app/pages/isolated-modules-onboarding/isolated-modules-onboarding.page.scss"]:::livre
  E497["src/app/pages/isolated-modules-onboarding/isolated-modules-onboarding.page.spec.ts"]:::livre
  E498["src/app/pages/isolated-modules-onboarding/isolated-modules-onboarding.page.ts"]:::livre
  E499["src/app/pages/languages-selection-settings/languages-selection-settings.module.ts"]:::livre
  E500["src/app/pages/languages-selection-settings/languages-selection-settings.page.html"]:::livre
  E501["src/app/pages/languages-selection-settings/languages-selection-settings.page.scss"]:::livre
  E502["src/app/pages/languages-selection-settings/languages-selection-settings.page.spec.ts"]:::livre
  E503["src/app/pages/languages-selection-settings/languages-selection-settings.page.ts"]:::livre
  E504["src/app/pages/link-page/link-page-routing.module.ts"]:::livre
  E505["src/app/pages/link-page/link-page.module.ts"]:::livre
  E506["src/app/pages/link-page/link-page.page.html"]:::livre
  E507["src/app/pages/link-page/link-page.page.scss"]:::livre
  E508["src/app/pages/link-page/link-page.page.spec.ts"]:::livre
  E509["src/app/pages/link-page/link-page.page.ts"]:::livre
  E510["src/app/pages/local-authentication-onboarding/local-authentication-onboarding.module.ts"]:::livre
  E511["src/app/pages/local-authentication-onboarding/local-authentication-onboarding.page.html"]:::livre
  E512["src/app/pages/local-authentication-onboarding/local-authentication-onboarding.page.scss"]:::livre
  E513["src/app/pages/local-authentication-onboarding/local-authentication-onboarding.page.spec.ts"]:::livre
  E514["src/app/pages/local-authentication-onboarding/local-authentication-onboarding.page.ts"]:::livre
  E515["src/app/pages/migration/migration-routing.module.ts"]:::livre
  E516["src/app/pages/migration/migration.actions.ts"]:::livre
  E517["src/app/pages/migration/migration.effects.ts"]:::livre
  E518["src/app/pages/migration/migration.module.ts"]:::livre
  E519["src/app/pages/migration/migration.page.html"]:::livre
  E520["src/app/pages/migration/migration.page.scss"]:::livre
  E521["src/app/pages/migration/migration.page.spec.ts"]:::livre
  E522["src/app/pages/migration/migration.page.ts"]:::livre
  E523["src/app/pages/migration/migration.reducers.ts"]:::livre
  E524["src/app/pages/migration/migration.types.ts"]:::livre
  E525["src/app/pages/migration/migration.utils.ts"]:::livre
  E526["src/app/pages/onboarding-advanced-mode/onboarding-advanced-mode.module.ts"]:::livre
  E527["src/app/pages/onboarding-advanced-mode/onboarding-advanced-mode.page.html"]:::livre
  E528["src/app/pages/onboarding-advanced-mode/onboarding-advanced-mode.page.scss"]:::livre
  E529["src/app/pages/onboarding-advanced-mode/onboarding-advanced-mode.page.spec.ts"]:::livre
  E530["src/app/pages/onboarding-advanced-mode/onboarding-advanced-mode.page.ts"]:::livre
  E531["src/app/pages/onboarding-welcome/onboarding-welcome.module.ts"]:::livre
  E532["src/app/pages/onboarding-welcome/onboarding-welcome.page.html"]:::livre
  E533["src/app/pages/onboarding-welcome/onboarding-welcome.page.scss"]:::livre
  E534["src/app/pages/onboarding-welcome/onboarding-welcome.page.spec.ts"]:::livre
  E535["src/app/pages/onboarding-welcome/onboarding-welcome.page.ts"]:::livre
  E536["src/app/pages/qr-settings/qr-settings-routing.module.ts"]:::livre
  E537["src/app/pages/qr-settings/qr-settings.module.ts"]:::livre
  E538["src/app/pages/qr-settings/qr-settings.page.html"]:::livre
  E539["src/app/pages/qr-settings/qr-settings.page.scss"]:::livre
  E540["src/app/pages/qr-settings/qr-settings.page.spec.ts"]:::livre
  E541["src/app/pages/qr-settings/qr-settings.page.ts"]:::livre
  E542["src/app/pages/scan-base/scan-base.ts"]:::livre
  E543["src/app/pages/secret-add/secret-add.module.ts"]:::livre
  E544["src/app/pages/secret-add/secret-add.page.html"]:::livre
  E545["src/app/pages/secret-add/secret-add.page.scss"]:::livre
  E546["src/app/pages/secret-add/secret-add.page.spec.ts"]:::livre
  E547["src/app/pages/secret-add/secret-add.page.ts"]:::livre
  E548["src/app/pages/secret-edit/secret-edit.module.ts"]:::livre
  E549["src/app/pages/secret-edit/secret-edit.page.html"]:::livre
  E550["src/app/pages/secret-edit/secret-edit.page.scss"]:::livre
  E551["src/app/pages/secret-edit/secret-edit.page.spec.ts"]:::livre
  E552["src/app/pages/secret-edit/secret-edit.page.ts"]:::livre
  E553["src/app/pages/secret-generate-coin-flip/secret-generate-coin-flip-routing.module.ts"]:::livre
  E554["src/app/pages/secret-generate-coin-flip/secret-generate-coin-flip.module.ts"]:::livre
  E555["src/app/pages/secret-generate-coin-flip/secret-generate-coin-flip.page.html"]:::livre
  E556["src/app/pages/secret-generate-coin-flip/secret-generate-coin-flip.page.scss"]:::livre
  E557["src/app/pages/secret-generate-coin-flip/secret-generate-coin-flip.page.spec.ts"]:::livre
  E558["src/app/pages/secret-generate-coin-flip/secret-generate-coin-flip.page.ts"]:::livre
  E559["src/app/pages/secret-generate-dice/secret-generate-dice-routing.module.ts"]:::livre
  E560["src/app/pages/secret-generate-dice/secret-generate-dice.module.ts"]:::livre
  E561["src/app/pages/secret-generate-dice/secret-generate-dice.page.html"]:::livre
  E562["src/app/pages/secret-generate-dice/secret-generate-dice.page.scss"]:::livre
  E563["src/app/pages/secret-generate-dice/secret-generate-dice.page.spec.ts"]:::livre
  E564["src/app/pages/secret-generate-dice/secret-generate-dice.page.ts"]:::livre
  E565["src/app/pages/secret-generate-onboarding/secret-generate-onboarding.module.ts"]:::livre
  E566["src/app/pages/secret-generate-onboarding/secret-generate-onboarding.page.html"]:::livre
  E567["src/app/pages/secret-generate-onboarding/secret-generate-onboarding.page.scss"]:::livre
  E568["src/app/pages/secret-generate-onboarding/secret-generate-onboarding.page.spec.ts"]:::livre
  E569["src/app/pages/secret-generate-onboarding/secret-generate-onboarding.page.ts"]:::livre
  E570["src/app/pages/secret-generate/secret-generate.module.ts"]:::livre
  E571["src/app/pages/secret-generate/secret-generate.page.html"]:::livre
  E572["src/app/pages/secret-generate/secret-generate.page.scss"]:::livre
  E573["src/app/pages/secret-generate/secret-generate.page.spec.ts"]:::livre
  E574["src/app/pages/secret-generate/secret-generate.page.ts"]:::livre
  E575["src/app/pages/secret-import/secret-import.module.ts"]:::livre
  E576["src/app/pages/secret-import/secret-import.page.html"]:::livre
  E577["src/app/pages/secret-import/secret-import.page.scss"]:::livre
  E578["src/app/pages/secret-import/secret-import.page.spec.ts"]:::livre
  E579["src/app/pages/secret-import/secret-import.page.ts"]:::livre
  E580["src/app/pages/secret-rules/secret-rules.module.ts"]:::livre
  E581["src/app/pages/secret-rules/secret-rules.page.html"]:::livre
  E582["src/app/pages/secret-rules/secret-rules.page.scss"]:::livre
  E583["src/app/pages/secret-rules/secret-rules.page.spec.ts"]:::livre
  E584["src/app/pages/secret-rules/secret-rules.page.ts"]:::livre
  E585["src/app/pages/secret-setup/secret-setup.module.ts"]:::livre
  E586["src/app/pages/secret-setup/secret-setup.page.html"]:::livre
  E587["src/app/pages/secret-setup/secret-setup.page.scss"]:::livre
  E588["src/app/pages/secret-setup/secret-setup.page.spec.ts"]:::livre
  E589["src/app/pages/secret-setup/secret-setup.page.ts"]:::livre
  E590["src/app/pages/secret-show/secret-show.module.ts"]:::livre
  E591["src/app/pages/secret-show/secret-show.page.html"]:::livre
  E592["src/app/pages/secret-show/secret-show.page.scss"]:::livre
  E593["src/app/pages/secret-show/secret-show.page.spec.ts"]:::livre
  E594["src/app/pages/secret-show/secret-show.page.ts"]:::livre
  E595["src/app/pages/secret-validate/secret-validate.module.ts"]:::livre
  E596["src/app/pages/secret-validate/secret-validate.page.html"]:::livre
  E597["src/app/pages/secret-validate/secret-validate.page.scss"]:::livre
  E598["src/app/pages/secret-validate/secret-validate.page.spec.ts"]:::livre
  E599["src/app/pages/secret-validate/secret-validate.page.ts"]:::livre
  E600["src/app/pages/security-level-self-check/security-level-self-check.module.ts"]:::livre
  E601["src/app/pages/security-level-self-check/security-level-self-check.page.html"]:::livre
  E602["src/app/pages/security-level-self-check/security-level-self-check.page.scss"]:::livre
  E603["src/app/pages/security-level-self-check/security-level-self-check.page.spec.ts"]:::livre
  E604["src/app/pages/security-level-self-check/security-level-self-check.page.ts"]:::livre
  E605["src/app/pages/select-account/select-account.module.ts"]:::livre
  E606["src/app/pages/select-account/select-account.page.html"]:::livre
  E607["src/app/pages/select-account/select-account.page.scss"]:::livre
  E608["src/app/pages/select-account/select-account.page.spec.ts"]:::livre
  E609["src/app/pages/select-account/select-account.page.ts"]:::livre
  E610["src/app/pages/shop/shop.module.ts"]:::livre
  E611["src/app/pages/shop/shop.page.html"]:::livre
  E612["src/app/pages/shop/shop.page.scss"]:::livre
  E613["src/app/pages/shop/shop.page.spec.ts"]:::livre
  E614["src/app/pages/shop/shop.page.ts"]:::livre
  E615["src/app/pages/social-recovery-generate-finish/social-recovery-generate-finish.module.ts"]:::livre
  E616["src/app/pages/social-recovery-generate-finish/social-recovery-generate-finish.page.html"]:::livre
  E617["src/app/pages/social-recovery-generate-finish/social-recovery-generate-finish.page.scss"]:::livre
  E618["src/app/pages/social-recovery-generate-finish/social-recovery-generate-finish.page.ts"]:::livre
  E619["src/app/pages/social-recovery-generate-finish/social-recovery-generate-finish.spec.ts"]:::livre
  E620["src/app/pages/social-recovery-generate-intro/social-recovery-generate-intro.module.ts"]:::livre
  E621["src/app/pages/social-recovery-generate-intro/social-recovery-generate-intro.page.html"]:::livre
  E622["src/app/pages/social-recovery-generate-intro/social-recovery-generate-intro.page.scss"]:::livre
  E623["src/app/pages/social-recovery-generate-intro/social-recovery-generate-intro.page.ts"]:::livre
  E624["src/app/pages/social-recovery-generate-intro/social-recovery-generate-intro.spec.ts"]:::livre
  E625["src/app/pages/social-recovery-generate-rules/social-recovery-generate-rules.module.ts"]:::livre
  E626["src/app/pages/social-recovery-generate-rules/social-recovery-generate-rules.page.html"]:::livre
  E627["src/app/pages/social-recovery-generate-rules/social-recovery-generate-rules.page.scss"]:::livre
  E628["src/app/pages/social-recovery-generate-rules/social-recovery-generate-rules.page.ts"]:::livre
  E629["src/app/pages/social-recovery-generate-rules/social-recovery-generate-rules.spec.ts"]:::livre
  E630["src/app/pages/social-recovery-generate-setup/social-recovery-generate-setup.module.ts"]:::livre
  E631["src/app/pages/social-recovery-generate-setup/social-recovery-generate-setup.page.html"]:::livre
  E632["src/app/pages/social-recovery-generate-setup/social-recovery-generate-setup.page.scss"]:::livre
  E633["src/app/pages/social-recovery-generate-setup/social-recovery-generate-setup.page.ts"]:::livre
  E634["src/app/pages/social-recovery-generate-setup/social-recovery-generate-setup.spec.ts"]:::livre
  E635["src/app/pages/social-recovery-generate-share-show/social-recovery-generate-share-show.module.ts"]:::livre
  E636["src/app/pages/social-recovery-generate-share-show/social-recovery-generate-share-show.page.html"]:::livre
  E637["src/app/pages/social-recovery-generate-share-show/social-recovery-generate-share-show.page.scss"]:::livre
  E638["src/app/pages/social-recovery-generate-share-show/social-recovery-generate-share-show.page.ts"]:::livre
  E639["src/app/pages/social-recovery-generate-share-show/social-recovery-generate-share-show.spec.ts"]:::livre
  E640["src/app/pages/social-recovery-generate-share-validate/social-recovery-generate-share-validate.module.ts"]:::livre
  E641["src/app/pages/social-recovery-generate-share-validate/social-recovery-generate-share-validate.page.html"]:::livre
  E642["src/app/pages/social-recovery-generate-share-validate/social-recovery-generate-share-validate.page.scss"]:::livre
  E643["src/app/pages/social-recovery-generate-share-validate/social-recovery-generate-share-validate.page.ts"]:::livre
  E644["src/app/pages/social-recovery-generate-share-validate/social-recovery-generate-share-validate.spec.ts"]:::livre
  E645["src/app/pages/social-recovery-import-errors/social-recovery-import-errors.module.ts"]:::livre
  E646["src/app/pages/social-recovery-import-errors/social-recovery-import-errors.page.html"]:::livre
  E647["src/app/pages/social-recovery-import-errors/social-recovery-import-errors.page.scss"]:::livre
  E648["src/app/pages/social-recovery-import-errors/social-recovery-import-errors.page.spec.ts"]:::livre
  E649["src/app/pages/social-recovery-import-errors/social-recovery-import-errors.page.ts"]:::livre
  E650["src/app/pages/social-recovery-import-help/social-recovery-import-help.module.ts"]:::livre
  E651["src/app/pages/social-recovery-import-help/social-recovery-import-help.page.html"]:::livre
  E652["src/app/pages/social-recovery-import-help/social-recovery-import-help.page.scss"]:::livre
  E653["src/app/pages/social-recovery-import-help/social-recovery-import-help.page.spec.ts"]:::livre
  E654["src/app/pages/social-recovery-import-help/social-recovery-import-help.page.ts"]:::livre
  E655["src/app/pages/social-recovery-import-intro/social-recovery-import-intro.module.ts"]:::livre
  E656["src/app/pages/social-recovery-import-intro/social-recovery-import-intro.page.html"]:::livre
  E657["src/app/pages/social-recovery-import-intro/social-recovery-import-intro.page.scss"]:::livre
  E658["src/app/pages/social-recovery-import-intro/social-recovery-import-intro.page.spec.ts"]:::livre
  E659["src/app/pages/social-recovery-import-intro/social-recovery-import-intro.page.ts"]:::livre
  E660["src/app/pages/social-recovery-import-setup/social-recovery-import-setup.module.ts"]:::livre
  E661["src/app/pages/social-recovery-import-setup/social-recovery-import-setup.page.html"]:::livre
  E662["src/app/pages/social-recovery-import-setup/social-recovery-import-setup.page.scss"]:::livre
  E663["src/app/pages/social-recovery-import-setup/social-recovery-import-setup.page.spec.ts"]:::livre
  E664["src/app/pages/social-recovery-import-setup/social-recovery-import-setup.page.ts"]:::livre
  E665["src/app/pages/social-recovery-import-share-name/social-recovery-import-share-name.module.ts"]:::livre
  E666["src/app/pages/social-recovery-import-share-name/social-recovery-import-share-name.page.html"]:::livre
  E667["src/app/pages/social-recovery-import-share-name/social-recovery-import-share-name.page.scss"]:::livre
  E668["src/app/pages/social-recovery-import-share-name/social-recovery-import-share-name.page.spec.ts"]:::livre
  E669["src/app/pages/social-recovery-import-share-name/social-recovery-import-share-name.page.ts"]:::livre
  E670["src/app/pages/social-recovery-import-share-validate/social-recovery-import-share-validate.module.ts"]:::livre
  E671["src/app/pages/social-recovery-import-share-validate/social-recovery-import-share-validate.page.html"]:::livre
  E672["src/app/pages/social-recovery-import-share-validate/social-recovery-import-share-validate.page.scss"]:::livre
  E673["src/app/pages/social-recovery-import-share-validate/social-recovery-import-share-validate.page.spec.ts"]:::livre
  E674["src/app/pages/social-recovery-import-share-validate/social-recovery-import-share-validate.page.ts"]:::livre
  E675["src/app/pages/social-recovery-import-success/social-recovery-import-success.module.ts"]:::livre
  E676["src/app/pages/social-recovery-import-success/social-recovery-import-success.page.html"]:::livre
  E677["src/app/pages/social-recovery-import-success/social-recovery-import-success.page.scss"]:::livre
  E678["src/app/pages/social-recovery-import-success/social-recovery-import-success.page.spec.ts"]:::livre
  E679["src/app/pages/social-recovery-import-success/social-recovery-import-success.page.ts"]:::livre
  E680["src/app/pages/social-recovery-import/social-recovery-import.module.ts"]:::livre
  E681["src/app/pages/social-recovery-import/social-recovery-import.page.html"]:::livre
  E682["src/app/pages/social-recovery-import/social-recovery-import.page.scss"]:::livre
  E683["src/app/pages/social-recovery-import/social-recovery-import.page.spec.ts"]:::livre
  E684["src/app/pages/social-recovery-import/social-recovery-import.page.ts"]:::livre
  E685["src/app/pages/social-recovery-setup/social-recovery-setup.module.ts"]:::livre
  E686["src/app/pages/social-recovery-setup/social-recovery-setup.page.html"]:::livre
  E687["src/app/pages/social-recovery-setup/social-recovery-setup.page.scss"]:::livre
  E688["src/app/pages/social-recovery-setup/social-recovery-setup.page.spec.ts"]:::livre
  E689["src/app/pages/social-recovery-setup/social-recovery-setup.page.ts"]:::livre
  E690["src/app/pages/social-recovery-show-share/social-recovery-show-share.module.ts"]:::livre
  E691["src/app/pages/social-recovery-show-share/social-recovery-show-share.page.html"]:::livre
  E692["src/app/pages/social-recovery-show-share/social-recovery-show-share.page.scss"]:::livre
  E693["src/app/pages/social-recovery-show-share/social-recovery-show-share.page.spec.ts"]:::livre
  E694["src/app/pages/social-recovery-show-share/social-recovery-show-share.page.ts"]:::livre
  E695["src/app/pages/social-recovery-validate-share/social-recovery-validate-share.module.ts"]:::livre
  E696["src/app/pages/social-recovery-validate-share/social-recovery-validate-share.page.html"]:::livre
  E697["src/app/pages/social-recovery-validate-share/social-recovery-validate-share.page.scss"]:::livre
  E698["src/app/pages/social-recovery-validate-share/social-recovery-validate-share.page.spec.ts"]:::livre
  E699["src/app/pages/social-recovery-validate-share/social-recovery-validate-share.page.ts"]:::livre
  E700["src/app/pages/tab-scan/tab-scan.module.ts"]:::livre
  E701["src/app/pages/tab-scan/tab-scan.page.html"]:::livre
  E702["src/app/pages/tab-scan/tab-scan.page.scss"]:::livre
  E703["src/app/pages/tab-scan/tab-scan.page.spec.ts"]:::livre
  E704["src/app/pages/tab-scan/tab-scan.page.ts"]:::livre
  E705["src/app/pages/tab-secrets/tab-secret-popover/tab-secret-popover.component.html"]:::livre
  E706["src/app/pages/tab-secrets/tab-secret-popover/tab-secret-popover.component.scss"]:::livre
  E707["src/app/pages/tab-secrets/tab-secret-popover/tab-secret-popover.component.spec.ts"]:::livre
  E708["src/app/pages/tab-secrets/tab-secret-popover/tab-secret-popover.component.ts"]:::livre
  E709["src/app/pages/tab-secrets/tab-secrets-routing.module.ts"]:::livre
  E710["src/app/pages/tab-secrets/tab-secrets.module.ts"]:::livre
  E711["src/app/pages/tab-secrets/tab-secrets.page.html"]:::livre
  E712["src/app/pages/tab-secrets/tab-secrets.page.scss"]:::livre
  E713["src/app/pages/tab-secrets/tab-secrets.page.spec.ts"]:::livre
  E714["src/app/pages/tab-secrets/tab-secrets.page.ts"]:::livre
  E715["src/app/pages/tab-settings/tab-settings.module.ts"]:::livre
  E716["src/app/pages/tab-settings/tab-settings.page.html"]:::livre
  E717["src/app/pages/tab-settings/tab-settings.page.scss"]:::livre
  E718["src/app/pages/tab-settings/tab-settings.page.spec.ts"]:::livre
  E719["src/app/pages/tab-settings/tab-settings.page.ts"]:::livre
  E720["src/app/pages/tabs/tabs.module.ts"]:::livre
  E721["src/app/pages/tabs/tabs.page.html"]:::livre
  E722["src/app/pages/tabs/tabs.page.scss"]:::livre
  E723["src/app/pages/tabs/tabs.page.spec.ts"]:::livre
  E724["src/app/pages/tabs/tabs.page.ts"]:::livre
  E725["src/app/pages/tabs/tabs.router.module.ts"]:::livre
  E726["src/app/pages/transaction-signed/transaction-signed.module.ts"]:::bloqueado
  E727["src/app/pages/transaction-signed/transaction-signed.page.html"]:::bloqueado
  E728["src/app/pages/transaction-signed/transaction-signed.page.scss"]:::bloqueado
  E729["src/app/pages/transaction-signed/transaction-signed.page.spec.ts"]:::bloqueado
  E730["src/app/pages/transaction-signed/transaction-signed.page.ts"]:::bloqueado
  E731["src/app/pages/vault-interaction-settings/vault-interaction-settings.module.ts"]:::livre
  E732["src/app/pages/vault-interaction-settings/vault-interaction-settings.page.html"]:::livre
  E733["src/app/pages/vault-interaction-settings/vault-interaction-settings.page.scss"]:::livre
  E734["src/app/pages/vault-interaction-settings/vault-interaction-settings.page.spec.ts"]:::livre
  E735["src/app/pages/vault-interaction-settings/vault-interaction-settings.page.ts"]:::livre
  E736["src/app/pages/warning-modal/warning-modal.module.ts"]:::livre
  E737["src/app/pages/warning-modal/warning-modal.page.html"]:::livre
  E738["src/app/pages/warning-modal/warning-modal.page.scss"]:::livre
  E739["src/app/pages/warning-modal/warning-modal.page.spec.ts"]:::livre
  E740["src/app/pages/warning-modal/warning-modal.page.ts"]:::livre
  E741["src/app/pages/wordlist/wordlist-routing.module.ts"]:::livre
  E742["src/app/pages/wordlist/wordlist.module.ts"]:::livre
  E743["src/app/pages/wordlist/wordlist.page.html"]:::livre
  E744["src/app/pages/wordlist/wordlist.page.scss"]:::livre
  E745["src/app/pages/wordlist/wordlist.page.spec.ts"]:::livre
  E746["src/app/pages/wordlist/wordlist.page.ts"]:::livre
  E747["src/app/pipes/pipes.module.ts"]:::livre
  E748["src/app/pipes/secret-filter/secret-filter.pipe.spec.ts"]:::livre
  E749["src/app/pipes/secret-filter/secret-filter.pipe.ts"]:::livre
  E750["src/app/pipes/wallet-status/wallet-status.pipe.spec.ts"]:::livre
  E751["src/app/pipes/wallet-status/wallet-status.pipe.ts"]:::livre
  E752["src/app/services/audio/audio.browser.service.ts"]:::livre
  E753["src/app/services/audio/audio.factory.ts"]:::livre
  E754["src/app/services/audio/audio.native.servive.ts"]:::livre
  E755["src/app/services/camera/camera.browser.service.ts"]:::livre
  E756["src/app/services/camera/camera.factory.ts"]:::livre
  E757["src/app/services/camera/camera.native.service.spec.ts"]:::livre
  E758["src/app/services/camera/camera.native.service.ts"]:::livre
  E759["src/app/services/coin-flip/coin-flip.service.spec.ts"]:::livre
  E760["src/app/services/coin-flip/coin-flip.service.ts"]:::livre
  E761["src/app/services/contacts/contacts.service.spec.ts"]:::livre
  E762["src/app/services/contacts/contacts.service.ts"]:::livre
  E763["src/app/services/device/device.service.spec.ts"]:::livre
  E764["src/app/services/device/device.service.ts"]:::livre
  E765["src/app/services/dice-roll/dice-roll.service.spec.ts"]:::livre
  E766["src/app/services/dice-roll/dice-roll.service.ts"]:::livre
  E767["src/app/services/entropy/IEntropyGenerator.ts"]:::livre
  E768["src/app/services/entropy/dummy.entropy.service.ts"]:::livre
  E769["src/app/services/entropy/entropy.service.spec.ts"]:::livre
  E770["src/app/services/entropy/entropy.service.ts"]:::livre
  E771["src/app/services/environment/vault-environment.service.ts"]:::livre
  E772["src/app/services/error-handler/error-handler.service.spec.ts"]:::livre
  E773["src/app/services/error-handler/error-handler.service.ts"]:::livre
  E774["src/app/services/gyroscope/gyroscope.factory.ts"]:::livre
  E775["src/app/services/gyroscope/gyroscope.native.service.ts"]:::livre
  E776["src/app/services/gyroscope/gyroscope.service.spec.ts"]:::livre
  E777["src/app/services/iac/iac.service.spec.ts"]:::livre
  E778["src/app/services/iac/iac.service.ts"]:::bloqueado
  E779["src/app/services/interaction/interaction.service.spec.ts"]:::livre
  E780["src/app/services/interaction/interaction.service.ts"]:::bloqueado
  E781["src/app/services/lifehash/lifehash.service.spec.ts"]:::livre
  E782["src/app/services/lifehash/lifehash.service.ts"]:::livre
  E783["src/app/services/migration/migration.service.ts"]:::livre
  E784["src/app/services/mode/mode.service.spec.ts"]:::livre
  E785["src/app/services/mode/mode.service.ts"]:::livre
  E786["src/app/services/mode/strategy/ModeStrategy.ts"]:::livre
  E787["src/app/services/mode/strategy/advanced-mode.service.ts"]:::livre
  E788["src/app/services/mode/strategy/basic-mode.service.ts"]:::livre
  E789["src/app/services/modules/modules.service.ts"]:::livre
  E790["src/app/services/navigation/navigation.service.spec.ts"]:::livre
  E791["src/app/services/navigation/navigation.service.ts"]:::livre
  E792["src/app/services/sapling-native/sapling-native.service.ts"]:::livre
  E793["src/app/services/secrets/secrets.service.spec.ts"]:::livre
  E794["src/app/services/secrets/secrets.service.ts"]:::livre
  E795["src/app/services/secure-storage/secure-storage.factory.ts"]:::livre
  E796["src/app/services/secure-storage/secure-storage.mock.ts"]:::livre
  E797["src/app/services/secure-storage/secure-storage.service.spec.ts"]:::livre
  E798["src/app/services/secure-storage/secure-storage.service.ts"]:::livre
  E799["src/app/services/share-url/share-url.service.spec.ts"]:::livre
  E800["src/app/services/share-url/share-url.service.ts"]:::livre
  E801["src/app/services/solflare-keystone/solflare-keystone.service.spec.ts"]:::bloqueado
  E802["src/app/services/solflare-keystone/solflare-keystone.service.ts"]:::bloqueado
  E803["src/app/services/startup-checks/startup-checks.service.spec.ts"]:::livre
  E804["src/app/services/startup-checks/startup-checks.service.ts"]:::livre
  E805["src/app/services/storage/storage.service.spec.ts"]:::livre
  E806["src/app/services/storage/storage.service.ts"]:::livre
  E807["src/app/services/token/TokenService.ts"]:::livre
  E808["src/app/social-recovery-import-share/social-recovery-import-share.service.ts"]:::livre
  E809["src/app/utils/migration.ts"]:::livre
  E810["src/app/utils/retry.ts"]:::livre
  E811["src/app/utils/utils.ts"]:::livre
  E812["src/app/validators/mnemonic.validator.ts"]:::livre
  E813["src/assets/i18n/de.json"]:::livre
  E814["src/assets/i18n/en.json"]:::livre
  E815["src/assets/i18n/es.json"]:::livre
  E816["src/assets/i18n/fr.json"]:::livre
  E817["src/assets/i18n/pt_BR.json"]:::livre
  E818["src/assets/i18n/ru.json"]:::livre
  E819["src/assets/i18n/zh_CN.json"]:::livre
  E820["src/assets/icon/favicon.png"]:::livre
  E821["src/assets/icons/extension-puzzle.svg"]:::livre
  E822["src/assets/icons/md-check.svg"]:::livre
  E823["src/assets/icons/md-edit.svg"]:::livre
  E824["src/assets/icons/md-fiber_manual_record.svg"]:::livre
  E825["src/assets/icons/md-fiber_pin.svg"]:::livre
  E826["src/assets/icons/md-group_work.svg"]:::livre
  E827["src/assets/icons/md-info.svg"]:::livre
  E828["src/assets/icons/md-mic.svg"]:::livre
  E829["src/assets/icons/md-people.svg"]:::livre
  E830["src/assets/icons/md-screen_rotation.svg"]:::livre
  E831["src/assets/icons/md-swap_horiz.svg"]:::livre
  E832["src/assets/icons/md-touch_app.svg"]:::livre
  E833["src/assets/icons/md-vertical_align_bottom.svg"]:::livre
  E834["src/assets/icons/md-videocam.svg"]:::livre
  E835["src/assets/icons/md-warning.svg"]:::livre
  E836["src/assets/icons/shapes.svg"]:::livre
  E837["src/assets/icons/shield-checkmark.svg"]:::livre
  E838["src/assets/img/2-apps-split.svg"]:::livre
  E839["src/assets/img/AirGap_Onboarding_Wallet.svg"]:::livre
  E840["src/assets/img/app-switching.svg"]:::livre
  E841["src/assets/img/clone.svg"]:::livre
  E842["src/assets/img/companion-apps.svg"]:::livre
  E843["src/assets/img/local_authentication_onboarding.svg"]:::livre
  E844["src/assets/img/logo.svg"]:::livre
  E845["src/assets/img/network_connection.svg"]:::livre
  E846["src/assets/img/no-wallet-added-onboarding.svg"]:::livre
  E847["src/assets/img/onboarding-advanced.svg"]:::livre
  E848["src/assets/img/onboarding-backup-seed-phrase.svg"]:::livre
  E849["src/assets/img/onboarding-offline.svg"]:::livre
  E850["src/assets/img/onboarding-peace-of-mind.svg"]:::livre
  E851["src/assets/img/onboarding-terms.svg"]:::livre
  E852["src/assets/img/onboarding-watch-only.svg"]:::livre
  E853["src/assets/img/permission_onboarding.svg"]:::livre
  E854["src/assets/img/permission_onboarding_camera.svg"]:::livre
  E855["src/assets/img/qr_code_guides.svg"]:::livre
  E856["src/assets/img/qrcode.svg"]:::livre
  E857["src/assets/img/root_detection.svg"]:::livre
  E858["src/assets/img/scan_confirmation_onboarding.svg"]:::livre
  E859["src/assets/img/screenshot_detected.svg"]:::livre
  E860["src/assets/img/send-one-device.svg"]:::livre
  E861["src/assets/img/send-two-device.svg"]:::livre
  E862["src/assets/img/shop.png"]:::livre
  E863["src/assets/img/social-group.svg"]:::livre
  E864["src/assets/img/social-group.xsd"]:::livre
  E865["src/assets/js/error-check.js"]:::livre
  E866["src/assets/logos/airgap-wallet-app-logo.png"]:::livre
  E867["src/assets/logos/airgap-wallet-app-logo.svg"]:::livre
  E868["src/assets/logos/bluewallet.png"]:::livre
  E869["src/assets/logos/imtoken-wallet.svg"]:::livre
  E870["src/assets/logos/metamask.webp"]:::livre
  E871["src/assets/logos/nunchuk.png"]:::livre
  E872["src/assets/logos/rabby-wallet.svg"]:::livre
  E873["src/assets/logos/sparrowwallet.png"]:::livre
  E874["src/assets/logos/specterwallet.png"]:::livre
  E875["src/assets/logos/superhero-wallet.png"]:::livre
  E876["src/assets/sapling/sapling-output.params"]:::livre
  E877["src/assets/sapling/sapling-spend.params"]:::livre
  E878["src/assets/workers/entropyCalculatorWorker.ts"]:::livre
  E879["src/assets/workers/hashWorker.ts"]:::livre
  E880["src/assets/workers/sha3.min.js"]:::livre
  E881["src/environments/environment.prod.ts"]:::livre
  E882["src/environments/environment.ts"]:::livre
  E883["src/global.scss"]:::livre
  E884["src/index.html"]:::livre
  E885["src/karma.conf.js"]:::livre
  E886["src/main.ts"]:::livre
  E887["src/manifest.webmanifest"]:::livre
  E888["src/polyfills.ts"]:::livre
  E889["src/test.ts"]:::livre
  E890["src/theme/variables.scss"]:::livre
  E891["src/tsconfig.app.json"]:::livre
  E892["src/tsconfig.spec.json"]:::livre
  E893["src/tslint.json"]:::livre
  E894["src/zone-flags.ts"]:::livre
  E895["test-config/ionic-mocks.ts"]:::livre
  E896["test-config/plugins-mocks.ts"]:::livre
  E897["test-config/storage-mock.ts"]:::livre
  E898["test-config/unit-test-helper.ts"]:::livre
  E899["test-config/wallet-mock.ts"]:::livre
  E900["tsconfig.json"]:::livre
  E901["tslint.json"]:::livre
  E902["uitest/README.md"]:::livre
  E903["uitest/config.json"]:::livre
  E904["uitest/pom.xml"]:::livre
  E905["uitest/src/main/resources/log4j.properties"]:::livre
  E906["uitest/src/test/java/Enums/TestResultStatus.java"]:::livre
  E907["uitest/src/test/java/Helpers/Config.java"]:::livre
  E908["uitest/src/test/java/Helpers/Log.java"]:::livre
  E909["uitest/src/test/java/Helpers/SleepExtension.java"]:::livre
  E910["uitest/src/test/java/Helpers/TakeScreenExtension.java"]:::livre
  E911["uitest/src/test/java/Helpers/TestResultLoggerExtension.java"]:::livre
  E912["uitest/src/test/java/Pages/AccountAdressPage.java"]:::livre
  E913["uitest/src/test/java/Pages/AddAccountPage.java"]:::livre
  E914["uitest/src/test/java/Pages/BasePage.java"]:::livre
  E915["uitest/src/test/java/Pages/MainPage.java"]:::livre
  E916["uitest/src/test/java/Pages/SaveSecretPage.java"]:::livre
  E917["uitest/src/test/java/Pages/Settings/EditSecretPage.java"]:::livre
  E918["uitest/src/test/java/Pages/Settings/SettingPage.java"]:::livre
  E919["uitest/src/test/java/Pages/Settings/SocialRevoveryPage.java"]:::livre
  E920["uitest/src/test/java/Pages/Welcome/DisclaimerPage.java"]:::livre
  E921["uitest/src/test/java/Pages/Welcome/GenerateSecretPage.java"]:::livre
  E922["uitest/src/test/java/Pages/Welcome/ImportPage.java"]:::livre
  E923["uitest/src/test/java/Pages/Welcome/SelectSecurityPage.java"]:::livre
  E924["uitest/src/test/java/Pages/Welcome/SetUpPage.java"]:::livre
  E925["uitest/src/test/java/TestFixtures/BaseTestFixture.java"]:::livre
  E926["uitest/src/test/java/Tests/GenerateSecretTest.java"]:::livre
  E927["uitest/src/test/java/Tests/ImportSecretTest.java"]:::livre
  E928["uitest/src/test/java/Tests/MultiAccountsTest.java"]:::livre
  E929["uitest/src/test/java/Tests/ParanoiaModeTest.java"]:::livre
  E930["uitest/src/test/java/Tests/SocialRecoveryTest.java.bak"]:::livre
  E931["yarn.lock"]:::bloqueado
  E932["scripts/airgap-vault-kaizou-nonregression.js"]:::bloqueado
  E933["scripts/airgap-vault-kaizou-karma.conf.js"]:::bloqueado
  E934["scripts/airgap-vault-kaizou-karma-gate.js"]:::bloqueado
  classDef bloqueado fill:#ffe3e3,stroke:#c92a2a
  classDef livre fill:#f8f9fa,stroke:#868e96
